#import "../nelson_help.typ": *

= rat <elementary_functions:2_elementary_math.rat>

Rational fraction approximation.

== Syntax

- #raw("[N, D] = rat(X)");
- #raw("[N, D] = rat(X, tol)");
- #raw("S = rat(X)");
- #raw("S = rat(X, tol)");

== Input argument

/ X: Input array: real or complex, scalar, vector or matrix (single or double).
/ tol: Tolerance: scalar. The default is #strong[1e-6 \* norm(X(:), 1)];.

== Output argument

/ N: Numerator: array of the same size as #strong[X];, or the continued fraction character array when a single output is requested.
/ D: Denominator: array of the same size as #strong[X];.

== Description

#strong[\[N, D\] \= rat(X)]; returns two integer arrays so that #strong[N .\/ D]; is close to #strong[X]; in the sense that #strong[abs(N .\/ D - X) \<\= tol];.

 The rational approximations are generated by truncating continued fraction expansions.

 #strong[S \= rat(X)]; returns the continued fraction representation as a character array.


== Example

``````matlab
[N, D] = rat(pi)
S = rat(pi)
``````


== See also

#nlink(<elementary_functions:2_elementary_math.rats>)[rats];, #nlink(<display_format:format>)[format];.

== History

#table(
  columns: 2,
  table.header([Version], [Description]),
  [2.0.0], [initial version],
)

// Author: Allan CORNET
