@echo off
REM Change to the directory of this script
cd /d %~dp0

echo Current directory: %cd%

REM Builds the Nelson PDF manuals from the Typst sources generated by
REM buildhelptypst (typst\<lang>\main.typ). No external tool is required
REM besides the Rust toolchain: the Typst compiler is linked into the builder.
REM Usage:
REM   build-pdf.bat           -> builds both 'en' and 'fr'
REM   build-pdf.bat en        -> builds only English
REM   build-pdf.bat fr        -> builds only French

set "SCRIPT_DIR=%~dp0"

set "LANGS=%~1"
if "%LANGS%"=="" set "LANGS=en,fr"

echo Building Rust PDF builder...
cargo build --release
if errorlevel 1 (
	echo ERROR: Rust PDF builder compilation failed
	exit /b 1
)
set "PDF_BUILDER=%SCRIPT_DIR%target\release\nelson-pdf-builder.exe"

"%PDF_BUILDER%" --languages "%LANGS%"
if errorlevel 1 (
	echo ERROR: Rust PDF builder failed
	exit /b 1
)

goto :eof
