#import "nelson_help.typ": *

= mexext <mex:mexext>

Binary MEX file-name extension

== Syntax

- #raw("ext = mexext()");
- #raw("extlist = mexext('all')");

== Description

#strong[ext \= mexext()]; returns the filename extension for the current platform.

 #strong[extlist \= mexext('all')]; returns the extensions for all platforms.

 A mex file is a type of computer file that provides an interface between Octave or the reference commercial software and functions written in C, C++.

 Nelson also provides its own C++ API to manage internal Nelson objects.

 

 Nelson cannot load mex files generated by other software, but you can rebuild them for each software target.

 Mex generated by Nelson have a file extension beginning by #strong[.nex];


== Example

``````matlab
ext = mexext()
extlist = mexext('all')
``````


== See also

#nlink(<mex:mex>)[mex];.

== History

#table(
  columns: 2,
  table.header([Version], [Description]),
  [1.0.0], [initial version],
)

// Author: Allan CORNET
