#import "nelson_help.typ": *

= cmake <dynamic_link:cmake>

call CMake tool

== Syntax

- #raw("[status, message] = cmake(varargin)");

== Input argument

/ varargin: command to send to CMake

== Output argument

/ res: a logical: true if cmake command is successfully
/ message: a string: message generated by cmake command.

== Description

#strong[cmake]; used internally to generate makefile used to build C\/C++ code.

 #strong[cmake]; used by #strong[dlgeneratemake];.


== See also

#nlink(<dynamic_link:dlgeneratemake>)[dlgeneratemake];, #nlink(<dynamic_link:dlmake>)[dlmake];.

== History

#table(
  columns: 2,
  table.header([Version], [Description]),
  [1.0.0], [initial version],
)

// Author: Allan CORNET
