#import "nelson_help.typ": nelson-style
#set document(title: "Nelson")
#show: nelson-style.with(lang: "fr")

#include "homepage.typ"
#pagebreak(weak: true)
#include "getting_started.typ"
#pagebreak(weak: true)
#include "functions_manager/main.typ"
#pagebreak(weak: true)
#include "modules_manager/main.typ"
#pagebreak(weak: true)
#include "core/main.typ"
#pagebreak(weak: true)
#include "engine/main.typ"
#pagebreak(weak: true)
#include "interpreter/main.typ"
#pagebreak(weak: true)
#include "error_manager/main.typ"
#pagebreak(weak: true)
#include "console/main.typ"
#pagebreak(weak: true)
#include "text_completion/main.typ"
#pagebreak(weak: true)
#include "display_format/main.typ"
#pagebreak(weak: true)
#include "characters_encoding/main.typ"
#pagebreak(weak: true)
#include "localization/main.typ"
#pagebreak(weak: true)
#include "i18n/main.typ"
#pagebreak(weak: true)
#include "types/main.typ"
#pagebreak(weak: true)
#include "logical/main.typ"
#pagebreak(weak: true)
#include "single/main.typ"
#pagebreak(weak: true)
#include "double/main.typ"
#pagebreak(weak: true)
#include "integer/main.typ"
#pagebreak(weak: true)
#include "sparse/main.typ"
#pagebreak(weak: true)
#include "string/main.typ"
#pagebreak(weak: true)
#include "function_handle/main.typ"
#pagebreak(weak: true)
#include "handle/main.typ"
#pagebreak(weak: true)
#include "data_structures/main.typ"
#pagebreak(weak: true)
#include "dictionary/main.typ"
#pagebreak(weak: true)
#include "table/main.typ"
#pagebreak(weak: true)
#include "categorical/main.typ"
#pagebreak(weak: true)
#include "overload/main.typ"
#pagebreak(weak: true)
#include "operators/main.typ"
#pagebreak(weak: true)
#include "constructors_functions/main.typ"
#pagebreak(weak: true)
#include "elementary_functions/main.typ"
#pagebreak(weak: true)
#include "trigonometric_functions/main.typ"
#pagebreak(weak: true)
#include "special_functions/main.typ"
#pagebreak(weak: true)
#include "linear_algebra/main.typ"
#pagebreak(weak: true)
#include "statistics/main.typ"
#pagebreak(weak: true)
#include "data_analysis/main.typ"
#pagebreak(weak: true)
#include "ode_solvers/main.typ"
#pagebreak(weak: true)
#include "polynomial_functions/main.typ"
#pagebreak(weak: true)
#include "geometry/main.typ"
#pagebreak(weak: true)
#include "control_system/main.typ"
#pagebreak(weak: true)
#include "slicot/main.typ"
#pagebreak(weak: true)
#include "signal_processing/main.typ"
#pagebreak(weak: true)
#include "fftw/main.typ"
#pagebreak(weak: true)
#include "random/main.typ"
#pagebreak(weak: true)
#include "os_functions/main.typ"
#pagebreak(weak: true)
#include "files_folders_functions/main.typ"
#pagebreak(weak: true)
#include "file_archiver/main.typ"
#pagebreak(weak: true)
#include "memory_manager/main.typ"
#pagebreak(weak: true)
#include "time/main.typ"
#pagebreak(weak: true)
#include "stream_manager/main.typ"
#pagebreak(weak: true)
#include "hdf5/main.typ"
#pagebreak(weak: true)
#include "netcdf/main.typ"
#pagebreak(weak: true)
#include "matio/main.typ"
#pagebreak(weak: true)
#include "xml/main.typ"
#pagebreak(weak: true)
#include "json/main.typ"
#pagebreak(weak: true)
#include "ai/main.typ"
#pagebreak(weak: true)
#include "parquet/main.typ"
#pagebreak(weak: true)
#include "spreadsheet/main.typ"
#pagebreak(weak: true)
#include "mpi/main.typ"
#pagebreak(weak: true)
#include "parallel/main.typ"
#pagebreak(weak: true)
#include "ipc/main.typ"
#pagebreak(weak: true)
#include "audio/main.typ"
#pagebreak(weak: true)
#include "history_manager/main.typ"
#pagebreak(weak: true)
#include "gui/main.typ"
#pagebreak(weak: true)
#include "qml_engine/main.typ"
#pagebreak(weak: true)
#include "text_editor/main.typ"
#pagebreak(weak: true)
#include "graphics/main.typ"
#pagebreak(weak: true)
#include "graphics_io/main.typ"
#pagebreak(weak: true)
#include "image_processing/main.typ"
#pagebreak(weak: true)
#include "webtools/main.typ"
#pagebreak(weak: true)
#include "webview/main.typ"
#pagebreak(weak: true)
#include "dynamic_link/main.typ"
#pagebreak(weak: true)
#include "mex/main.typ"
#pagebreak(weak: true)
#include "f2c/main.typ"
#pagebreak(weak: true)
#include "validators/main.typ"
#pagebreak(weak: true)
#include "python_engine/main.typ"
#pagebreak(weak: true)
#include "julia_engine/main.typ"
#pagebreak(weak: true)
#include "gpu_engine/main.typ"
#pagebreak(weak: true)
#include "debugger/main.typ"
#pagebreak(weak: true)
#include "profiler/main.typ"
#pagebreak(weak: true)
#include "tests_manager/main.typ"
#pagebreak(weak: true)
#include "assert_functions/main.typ"
#pagebreak(weak: true)
#include "help_tools/main.typ"
#pagebreak(weak: true)
#include "optimization/main.typ"
#pagebreak(weak: true)
#include "nflow_blocks/main.typ"
#pagebreak(weak: true)
#include "nflow_engine/main.typ"
#pagebreak(weak: true)
#include "nflow_fmi/main.typ"
#pagebreak(weak: true)
#include "nflow_gui/main.typ"
#pagebreak(weak: true)
#include "nmm_gui/main.typ"
#pagebreak(weak: true)
#include "compiler/main.typ"
#pagebreak(weak: true)
#include "changelogs/CHANGELOG.typ"
#pagebreak(weak: true)
#include "changelogs/CHANGELOG-1.x.x.typ"
#pagebreak(weak: true)
#include "changelogs/CHANGELOG-0.7.x.typ"
#pagebreak(weak: true)
#include "changelogs/CHANGELOG-0.6.x.typ"
#pagebreak(weak: true)
#include "changelogs/CHANGELOG-0.5.x.typ"
#pagebreak(weak: true)
#include "changelogs/CHANGELOG-0.4.x.typ"
#pagebreak(weak: true)
#include "changelogs/CHANGELOG-0.3.x.typ"
#pagebreak(weak: true)
#include "changelogs/CHANGELOG-0.2.x.typ"
#pagebreak(weak: true)
#include "changelogs/CHANGELOG-0.1.x.typ"
#pagebreak(weak: true)
#include "license/license.typ"
#pagebreak(weak: true)
#include "license/lgpl-3.0.typ"
#pagebreak(weak: true)
#include "license/gpl-3.0.typ"
#pagebreak(weak: true)
#outline(depth: 2)
