#import "../nelson_help.typ": *

= openfig <graphics:5_printing_saving.openfig>

Open a Nelson FIG file.

== Syntax

- #raw("openfig()");
- #raw("openfig(filename)");
- #raw("openfig(filename, copies)");
- #raw("openfig(filename, visibility)");
- #raw("openfig(filename, copies, visibility)");
- #raw("fig = openfig(...)");

== Input argument

/ filename: Character vector or string scalar naming a Nelson #strong[.fig]; file. If filename has no extension, #strong[openfig]; appends #strong[.fig];. The default is #strong[Untitled.fig];.
/ copies: #strong['new']; or #strong['reuse'];. The default is #strong['new'];. Use #strong['reuse']; to return an already opened figure whose #strong[FileName]; property matches the requested file.
/ visibility: #strong['visible']; or #strong['invisible'];. This option overrides the saved visible state after the figure is restored or reused.

== Output argument

/ fig: Opened figure graphics object or array of figure graphics objects. If the file contains several saved figures, all restored figures are returned.

== Description

#strong[openfig()]; opens #strong[Untitled.fig];.

 #strong[openfig(filename)]; opens the figure or figures stored in #strong[filename]; and creates new figure objects.

 #strong[openfig(filename, 'new')]; always creates new figure objects. This is the default behavior.

 #strong[openfig(filename, 'reuse')]; first searches opened figures whose #strong[FileName]; property matches the resolved file path. If such figures exist, they are returned instead of loading a new copy.

 #strong[openfig(filename, visibility)]; or #strong[openfig(filename, copies, visibility)]; controls whether restored or reused figures are visible.

 Each restored figure receives a #strong[FileName]; property equal to the resolved #strong[.fig]; path. This allows later calls with #strong['reuse']; to find it.

 #strong[Warning:]; Nelson #strong[.fig]; files are Nelson-specific. Files not generated by Nelson are not supported.

 The restored objects are new graphics objects. Most persistent properties saved by #strong[savefig]; are restored, while current defaults and runtime-only state can still affect the newly created figures.


== Examples

Save a figure, close it, and reopen it later.

``````matlab

x = linspace(0, 10);
y = sin(x);
f = figure('Visible', 'off');
plot(x, y);
title('Sine Wave');
xlabel('x ranges from 0 to 10');
ylabel('y = sin(x)');
figfile = [tempname(), '_SineWave.fig'];
savefig(f, figfile);
close(f);
restored = openfig(figfile, 'invisible');
assert(isgraphics(restored, 'figure'));
close(restored);

``````

Open a saved invisible figure in visible state.

``````matlab

f = figure('Visible', 'off');
plot(1:5);
figfile = [tempname(), '_visible_on_open.fig'];
savefig(f, figfile);
close(f);
restored = openfig(figfile, 'visible');
assert(strcmp(char(get(restored, 'Visible')), 'on'));
close(restored);

``````

Reuse an already opened figure.

``````matlab

f = figure('Visible', 'off');
plot([3 1 4 1 5]);
figfile = [tempname(), '_reuse_example.fig'];
savefig(f, figfile);
close(f);
first = openfig(figfile, 'invisible');
second = openfig(figfile, 'reuse', 'invisible');
assert(isequal(first, second));
close(first);

``````

Open a file containing several figures.

``````matlab

figs(1) = figure('Visible', 'off');
plot(1:4);
figs(2) = figure('Visible', 'off');
stairs([4 2 3]);
figfile = [tempname(), '_many_figures.fig'];
savefig(figs, figfile);
close(figs);
restored = openfig(figfile, 'invisible');
assert(isequal(numel(restored), 2));
close(restored);

``````


== See also

#nlink(<graphics:5_printing_saving.savefig>)[savefig];, #nlink(<graphics:2_graphics_objects.1_object_management.figure>)[figure];, #nlink(<graphics:2_graphics_objects.1_object_management.close>)[close];, #nlink(<hdf5:loadnh5>)[loadnh5];.

== History

#table(
  columns: 2,
  table.header([Version], [Description]),
  [2.0.0], [initial version],
)

// Author: Allan CORNET
