#import "../nelson_help.typ": *

= savefig <graphics:5_printing_saving.savefig>

Save figure to a Nelson FIG file.

== Syntax

- #raw("savefig()");
- #raw("savefig(filename)");
- #raw("savefig(fig, filename)");
- #raw("savefig(fig, filename, version)");

== Input argument

/ fig: Figure graphics object or array of figure graphics objects. Every element must be a valid figure.
/ filename: Character vector or string scalar. If filename has no extension, #strong[savefig]; appends #strong[.fig];. Other extensions are rejected.
/ version: Compatibility flag accepted for syntax compatibility: #strong['-v7.3'];, #strong['-v7'];, or #strong['-v6'];. Nelson stores the same Nelson FIG format for each value.

== Description

#strong[savefig()]; saves the current figure returned by #strong[gcf()]; to #strong[Untitled.fig];.

 #strong[savefig(filename)]; saves the current figure to #strong[filename];.

 #strong[savefig(fig, filename)]; saves the specified figure or array of figures to one file.

 #strong[savefig(fig, filename, version)]; accepts a version flag for syntax compatibility. The flag does not change the Nelson file layout.

 The saved file contains a Nelson-owned figure payload stored in an HDF5\/NH5 container. It is intended for reopening figures with #strong[openfig];, including their graphics object tree and supported persistent properties.

 #strong[Warning:]; Nelson #strong[.fig]; files are Nelson-specific. They are not compatible with #strong[.fig]; files that were not generated by Nelson, and Nelson does not guarantee that non-Nelson #strong[.fig]; files can be opened.

 #strong[savefig]; stores complete figures. To export a bitmap or vector image for publication, use image export functions such as #strong[saveas]; when available. To save workspace variables, use data save functions instead.

 Runtime-only values such as live graphics handles embedded in arbitrary properties and function handles are not restored as portable figure state.


== Examples

Save the current figure and reopen it.

``````matlab

f = figure('Visible', 'off');
plot(1:5, [1 4 9 16 25]);
title('Quadratic data');
figfile = [tempname(), '_quadratic.fig'];
savefig(figfile);
close(f);
restored = openfig(figfile, 'invisible');
assert(isgraphics(restored, 'figure'));
close(restored);

``````

Save with automatic .fig extension.

``````matlab

f = figure('Visible', 'off');
plot(1:3);
figfile = [tempname(), '_auto_extension'];
savefig(f, figfile);
assert(isfile([figfile, '.fig']));
close(f);

``````

Save multiple figures in one file.

``````matlab

figs(1) = figure('Visible', 'off');
plot(1:4);
figs(2) = figure('Visible', 'off');
bar([2 4 3]);
figfile = [tempname(), '_two_figures.fig'];
savefig(figs, figfile);
close(figs);
restored = openfig(figfile, 'invisible');
assert(isequal(numel(restored), 2));
close(restored);

``````

Use a version flag accepted for compatibility.

``````matlab

f = figure('Visible', 'off');
surf(peaks());
figfile = [tempname(), '_surface.fig'];
savefig(f, figfile, '-v7.3');
close(f);

``````


== See also

#nlink(<graphics:5_printing_saving.openfig>)[openfig];, #nlink(<graphics:2_graphics_objects.1_object_management.gcf>)[gcf];, #nlink(<graphics_io:saveas>)[saveas];, #nlink(<hdf5:savenh5>)[savenh5];.

== History

#table(
  columns: 2,
  table.header([Version], [Description]),
  [2.0.0], [initial version],
)

// Author: Allan CORNET
