// =============================================================================
// Copyright (c) 2016-present Allan CORNET (Nelson)
// =============================================================================
// This file is part of Nelson.
// =============================================================================
// LICENCE_BLOCK_BEGIN
// SPDX-License-Identifier: LGPL-3.0-or-later
// LICENCE_BLOCK_END
// =============================================================================
// Shared helpers for the Typst help pages generated by xmldoctotypst.
// Every generated page imports this file from the module root directory.
// =============================================================================

// Cross-reference to another help page. The target is a label of the form
// <module:page>. It becomes a link when the page is part of the compiled
// document and stays plain text otherwise (for example a page of another
// module that was not generated).
#let nlink(target, body) = context {
  if query(target).len() > 0 { link(target, body) } else { body }
}

// Include content one heading level below the current one, so a page whose
// title is a level-1 heading nests correctly under its chapter.
#let nested(body) = context {
  let offset = heading.offset
  [
    #set heading(offset: offset + 1)
    #body
  ]
}

// LaTeX fragments of the XML sources are rendered with the mitex package
// (LaTeX to Typst math, WebAssembly plugin). The typst CLI downloads it from
// Typst Universe; the Nelson PDF builder resolves it from its vendored copy
// under theme/typst-packages/preview/mitex/0.2.7. A fragment containing an
// environment or a line break is typeset as a display equation, the others
// inline.
#import "@preview/mitex:0.2.7": mitex, mi
#let latex(src) = if src.contains("\\begin") or src.contains("\\\\") {
  mitex(src)
} else {
  mi(src)
}

// Icon of a block library (SVG export under libraries/<lib>/exports/). The
// page passes the image itself (paths are resolved relative to the calling
// file). Shown with the proportions of the HTML help, where the icon is
// capped at 192 x 144 CSS pixels for a 16 px body text: at most 12 x 9 em
// of the current text size, never enlarged, centered in a thin bordered box.
#let block-icon(img) = context {
  let natural = measure(img)
  let max-width = (12em).to-absolute()
  let max-height = (9em).to-absolute()
  let k = calc.min(1.0, max-width / natural.width, max-height / natural.height)
  block(width: 100%, above: 0.8em, below: 0.8em, align(center, box(
    fill: white,
    stroke: 0.5pt + rgb("#e2e8f0"),
    radius: 4pt,
    inset: 6pt,
    scale(k * 100%, reflow: true, img),
  )))
}

// Reference to a whole source file (manifest, handler): the listing is not
// printed, it would add thousands of pages of duplicated JSON/C++ to the
// manual. Only bounded excerpts
// (start/end attributes of <source_code>) are printed with source-code.
#let source-ref(path, title: "Source") = block(
  width: 100%,
  inset: 6pt,
  stroke: 0.5pt + luma(180),
  radius: 3pt,
)[
  #text(size: 0.9em)[*#title:* #raw(path)]
]

// Source listing injected from the repository at build time.
#let source-code(path, title: "Source", body) = block(
  width: 100%,
  inset: 8pt,
  stroke: 0.5pt + luma(180),
  radius: 3pt,
)[
  #text(size: 0.9em)[*#title:* #raw(path)]
  #body
]

// Document style of the printed manual, transposed from the CSS of the former
// HTML/PDF chain: sans-serif body text, compact headings, grey code boxes,
// blue table headers, blue links with a marker on external ones, and a
// "Page X of Y" footer. Applied by the generated main.typ with
//   #show: nelson-style.with(lang: "en")
#let nelson-style(lang: "en", body) = {
  set text(
    // Noto Sans (vendored in theme/fonts of nelson-gitbook, so the manual
    // renders the same on every platform), then Noto Sans Math, Noto Sans JP
    // and Noto Emoji for the symbols, Japanese examples and emoji it does not
    // cover, then the system Segoe UI and the Libertinus Serif embedded in
    // the builder.
    font: ("Noto Sans", "Noto Sans Math", "Noto Sans JP", "Noto Emoji", "Segoe UI", "Libertinus Serif"),
    size: 10.5pt,
    fill: rgb("#222222"),
    lang: lang,
  )
  set par(justify: false, leading: 0.55em, spacing: 0.9em)
  set page(
    paper: "a4",
    margin: (x: 16mm, y: 16mm),
    numbering: "1",
    footer: context align(center, text(size: 9pt, fill: luma(90))[
      Page #counter(page).display() #(if lang == "fr" { "sur" } else { "of" }) #counter(page).final().first()
    ]),
  )
  // headings: chapter (level 1) with a blue rule, page title (level 2) 18 pt,
  // page sections (level 3) 14.5 pt; only chapters and pages are outlined
  show heading: set text(fill: rgb("#1a1a1a"))
  show heading.where(level: 1): it => block(width: 100%, above: 1.2em, below: 1em)[
    #text(size: 22pt, weight: 700)[#it.body]
    #v(3pt)
    #line(length: 100%, stroke: 1pt + rgb("#2b7cd3"))
  ]
  show heading.where(level: 2): set text(size: 18pt)
  show heading.where(level: 2): set block(above: 1.1em, below: 0.6em)
  show heading.where(level: 3): set text(size: 14.5pt)
  show heading.where(level: 3): set block(above: 1em, below: 0.45em)
  show heading.where(level: 4): set text(size: 12.5pt)
  show heading.where(level: 3): set heading(outlined: false)
  show heading.where(level: 4): set heading(outlined: false)
  // code
  // code: JetBrains Mono (vendored), the embedded DejaVu Sans Mono for the
  // Latin and Cyrillic letters it lacks, Noto Sans JP for Japanese examples
  show raw: set text(font: ("JetBrains Mono", "DejaVu Sans Mono", "Noto Sans JP"), size: 9pt, fill: rgb("#111111"))
  show raw.where(block: true): it => block(
    width: 100%,
    fill: rgb("#f5f7fa"),
    radius: 4pt,
    inset: (x: 10pt, y: 8pt),
    it,
  )
  show raw.where(block: false): it => box(
    fill: rgb("#f5f7fa"),
    inset: (x: 3pt, y: 0pt),
    outset: (y: 2pt),
    radius: 2pt,
    it,
  )
  // links: blue, external ones marked
  show link: it => {
    set text(fill: rgb("#0b66ff"))
    it
    if type(it.dest) == str {
      text(size: 0.85em, fill: luma(110))[ (↗)]
    }
  }
  // tables: blue header row, light borders, zebra rows
  set table(
    stroke: 0.5pt + rgb("#e1e5ea"),
    inset: (x: 8pt, y: 5pt),
    fill: (_, y) => if y == 0 { rgb("#2b7cd3") } else if calc.even(y) { rgb("#fbfdff") } else { white },
  )
  show table: set text(size: 9pt)
  show table.cell.where(y: 0): set text(fill: white, weight: 600)
  // quotes
  show quote.where(block: true): set block(
    stroke: (left: 4pt + rgb("#d0d7de")),
    inset: (left: 12pt, y: 6pt),
    fill: rgb("#fbfcfd"),
  )
  body
}
