#import "../../nelson_help.typ": *

= polaraxes properties <graphics:2_graphics_objects.4_properties.nelson.graphics.polaraxes.properties>

polaraxes graphics object properties.

== Description

This page documents the visible properties returned by #strong[properties]; for a #strong[polaraxes]; graphics object.

 

#table(
  columns: 3,
  [Property], [Action], [Type and supported values], 
  [#strong[ALim];], [recomputes geometry, limits, or layout.], [Type: finite numeric vector. Supported values: two finite increasing values \[min max\].], 
  [#strong[ALimMode];], ['auto' lets Nelson recompute the paired property; 'manual' preserves the assigned value.], [Type: text scalar or character row vector. Supported values: 'auto', 'manual'.], 
  [#strong[AlphaScale];], [updates rendered output on the next graphics refresh.], [Type: text scalar or character row vector. Supported values: 'linear', 'log'.], 
  [#strong[Alphamap];], [updates rendered output on the next graphics refresh.], [Type: finite numeric vector. Supported values: numeric alpha values in \[0,1\].], 
  [#strong[AmbientLightColor];], [updates rendered output on the next graphics refresh.], [Type: color value. Supported values: 'red'\/'r', 'green'\/'g', 'blue'\/'b', 'cyan'\/'c', 'magenta'\/'m', 'yellow'\/'y', 'black'\/'k', 'white'\/'w', RGB triplet \[r g b\] with values in \[0,1\], or hexadecimal color '\#RRGGBB'\/'\#RGB'.], 
  [#strong[BeingDeleted];], [Nelson computes this value; graphics operations update it.], [Type: text scalar or character row vector. Supported values: 'off', 'on'.], 
  [#strong[Box];], [updates rendered output on the next graphics refresh.], [Type: on\/off value. Supported values: 'on', 'off', true, or false.], 
  [#strong[BoxStyle];], [updates rendered output on the next graphics refresh.], [Type: text scalar or character row vector. Supported values: style names defined by this object, such as UI styles, light styles, chart styles, or line styles.], 
  [#strong[BusyAction];], [controls whether an interrupting callback is queued or canceled.], [Type: text scalar or character row vector. Supported values: 'queue', 'cancel'.], 
  [#strong[ButtonDownFcn];], [runs when the object receives a mouse-button event.], [Type: callback value. Supported values: \[\], function handle, character vector, string scalar, or callback cell array.], 
  [#strong[CLim];], [recomputes geometry, limits, or layout.], [Type: finite numeric vector. Supported values: two finite increasing values \[min max\].], 
  [#strong[CLimMode];], ['auto' lets Nelson recompute the paired property; 'manual' preserves the assigned value.], [Type: text scalar or character row vector. Supported values: 'auto', 'manual'.], 
  [#strong[CameraPosition];], [recomputes geometry, limits, or layout.], [Type: finite numeric vector. Supported values: finite vector with the documented size, such as \[left bottom width height\], \[x y z\], \[azimuth elevation\], or \[minor major\].], 
  [#strong[CameraPositionMode];], ['auto' lets Nelson recompute the paired property; 'manual' preserves the assigned value.], [Type: text scalar or character row vector. Supported values: 'auto', 'manual'.], 
  [#strong[CameraTarget];], [recomputes geometry, limits, or layout.], [Type: finite numeric vector. Supported values: finite vector with the documented size, such as \[left bottom width height\], \[x y z\], \[azimuth elevation\], or \[minor major\].], 
  [#strong[CameraTargetMode];], ['auto' lets Nelson recompute the paired property; 'manual' preserves the assigned value.], [Type: text scalar or character row vector. Supported values: 'auto', 'manual'.], 
  [#strong[CameraUpVector];], [recomputes geometry, limits, or layout.], [Type: finite numeric vector. Supported values: finite vector with the documented size, such as \[left bottom width height\], \[x y z\], \[azimuth elevation\], or \[minor major\].], 
  [#strong[CameraUpVectorMode];], ['auto' lets Nelson recompute the paired property; 'manual' preserves the assigned value.], [Type: text scalar or character row vector. Supported values: 'auto', 'manual'.], 
  [#strong[CameraViewAngle];], [recomputes geometry, limits, or layout.], [Type: finite numeric vector. Supported values: finite vector with the documented size, such as \[left bottom width height\], \[x y z\], \[azimuth elevation\], or \[minor major\].], 
  [#strong[CameraViewAngleMode];], ['auto' lets Nelson recompute the paired property; 'manual' preserves the assigned value.], [Type: text scalar or character row vector. Supported values: 'auto', 'manual'.], 
  [#strong[Children];], [parenting operations update the vector.], [Type: graphics object handle vector. Supported values: empty vector or child handles.], 
  [#strong[Clipping];], [updates rendered output on the next graphics refresh.], [Type: text scalar or character row vector. Supported values: 'on', 'off'.], 
  [#strong[ClippingStyle];], [updates rendered output on the next graphics refresh.], [Type: text scalar or character row vector. Supported values: style names defined by this object, such as UI styles, light styles, chart styles, or line styles.], 
  [#strong[Color];], [updates rendered output on the next graphics refresh.], [Type: color value. Supported values: 'red'\/'r', 'green'\/'g', 'blue'\/'b', 'cyan'\/'c', 'magenta'\/'m', 'yellow'\/'y', 'black'\/'k', 'white'\/'w', RGB triplet \[r g b\] with values in \[0,1\], or hexadecimal color '\#RRGGBB'\/'\#RGB'.], 
  [#strong[ColorOrder];], [changes automatically selected colors for subsequent plotted series.], [Type: finite numeric matrix. Supported values: m-by-3 RGB matrix with values in \[0,1\].], 
  [#strong[ColorOrderIndex];], [updates rendered output on the next graphics refresh.], [Type: color value. Supported values: 'red'\/'r', 'green'\/'g', 'blue'\/'b', 'cyan'\/'c', 'magenta'\/'m', 'yellow'\/'y', 'black'\/'k', 'white'\/'w', RGB triplet \[r g b\] with values in \[0,1\], or hexadecimal color '\#RRGGBB'\/'\#RGB'.], 
  [#strong[ColorScale];], [updates rendered output on the next graphics refresh.], [Type: color value. Supported values: 'red'\/'r', 'green'\/'g', 'blue'\/'b', 'cyan'\/'c', 'magenta'\/'m', 'yellow'\/'y', 'black'\/'k', 'white'\/'w', RGB triplet \[r g b\] with values in \[0,1\], or hexadecimal color '\#RRGGBB'\/'\#RGB'.], 
  [#strong[Colormap];], [updates rendered output on the next graphics refresh.], [Type: finite numeric matrix. Supported values: m-by-3 RGB matrix with values in \[0,1\].], 
  [#strong[ContextMenu];], [attaches the menu used for context-click actions.], [Type: graphics object handle scalar. Supported values: \[\] or a uicontextmenu handle.], 
  [#strong[CreateFcn];], [runs when the object is created.], [Type: callback value. Supported values: \[\], function handle, character vector, string scalar, or callback cell array.], 
  [#strong[CurrentPoint];], [pointer location in data coordinates, updated on the same mouse events as the figure CurrentPoint, for axes placed directly in the figure or in a panel, tab or tiled layout.], [Type: 2-by-3 matrix \[xfront yfront zfront; xback yback zback\]. Supported values: the front and back points of the view line under the pointer, cut at the axes box; in a 2-D view both rows share x and y and z is the upper then the lower z-limit. Log scales and reversed directions are taken into account.], 
  [#strong[DataAspectRatio];], [recomputes geometry, limits, or layout.], [Type: finite numeric vector. Supported values: finite vector with the documented size, such as \[left bottom width height\], \[x y z\], \[azimuth elevation\], or \[minor major\].], 
  [#strong[DataAspectRatioMode];], ['auto' lets Nelson recompute the paired property; 'manual' preserves the assigned value.], [Type: text scalar or character row vector. Supported values: 'auto', 'manual'.], 
  [#strong[DataLimits];], [recomputes geometry, limits, or layout.], [Type: finite numeric vector. Supported values: two finite increasing values \[min max\].], 
  [#strong[DeleteFcn];], [runs when the object is deleted.], [Type: callback value. Supported values: \[\], function handle, character vector, string scalar, or callback cell array.], 
  [#strong[FontAngle];], [updates rendered output on the next graphics refresh.], [Type: text scalar or character row vector. Supported values: 'normal', 'italic'.], 
  [#strong[FontName];], [updates rendered output on the next graphics refresh.], [Type: text scalar or character row vector. Supported values: a system font name or 'FixedWidth'.], 
  [#strong[FontSize];], [recomputes geometry, limits, or layout.], [Type: finite numeric scalar. Supported values: finite scalar value.], 
  [#strong[FontSizeMode];], ['auto' lets Nelson recompute the paired property; 'manual' preserves the assigned value.], [Type: text scalar or character row vector. Supported values: 'auto', 'manual'.], 
  [#strong[FontSmoothing];], [updates rendered output on the next graphics refresh.], [Type: on\/off value. Supported values: 'on', 'off', true, or false.], 
  [#strong[FontUnits];], [recomputes geometry, limits, or layout.], [Type: text scalar or character row vector. Supported values: 'pixels', 'normalized', 'inches', 'centimeters', 'points', 'characters', 'data'.], 
  [#strong[FontWeight];], [updates rendered output on the next graphics refresh.], [Type: text scalar or character row vector. Supported values: 'normal', 'bold'.], 
  [#strong[GridAlpha];], [updates rendered output on the next graphics refresh.], [Type: numeric scalar or numeric array. Supported values: values in \[0,1\]; data arrays must match the related rendered data.], 
  [#strong[GridAlphaMode];], ['auto' lets Nelson recompute the paired property; 'manual' preserves the assigned value.], [Type: text scalar or character row vector. Supported values: 'auto', 'manual'.], 
  [#strong[GridColor];], [updates rendered output on the next graphics refresh.], [Type: color value. Supported values: 'red'\/'r', 'green'\/'g', 'blue'\/'b', 'cyan'\/'c', 'magenta'\/'m', 'yellow'\/'y', 'black'\/'k', 'white'\/'w', RGB triplet \[r g b\] with values in \[0,1\], or hexadecimal color '\#RRGGBB'\/'\#RGB'.], 
  [#strong[GridColorMode];], ['auto' lets Nelson recompute the paired property; 'manual' preserves the assigned value.], [Type: text scalar or character row vector. Supported values: 'auto', 'manual'.], 
  [#strong[GridLineStyle];], [updates rendered output on the next graphics refresh.], [Type: text scalar or character row vector. Supported values: '-', '--', ':', '-.', 'none'.], 
  [#strong[GridLineWidth];], [updates rendered output on the next graphics refresh.], [Type: finite numeric scalar. Supported values: value greater than or equal to 0.], 
  [#strong[GridLineWidthMode];], ['auto' lets Nelson recompute the paired property; 'manual' preserves the assigned value.], [Type: text scalar or character row vector. Supported values: 'auto', 'manual'.], 
  [#strong[HandleVisibility];], [controls whether handle-search functions can find the object.], [Type: text scalar or character row vector. Supported values: 'on', 'off', 'callback'.], 
  [#strong[HitTest];], [includes or excludes the object from mouse hit testing.], [Type: text scalar or character row vector. Supported values: 'on', 'off'.], 
  [#strong[InnerPosition];], [recomputes geometry, limits, or layout.], [Type: finite numeric vector. Supported values: finite vector with the documented size, such as \[left bottom width height\], \[x y z\], \[azimuth elevation\], or \[minor major\].], 
  [#strong[InteractionOptions];], [updates the stored object state.], [Type: interaction object, structure, cell array, or empty array. Supported values: \[\] or interaction definitions for axes and charts.], 
  [#strong[Interactions];], [updates the stored object state.], [Type: interaction object, structure, cell array, or empty array. Supported values: \[\] or interaction definitions for axes and charts.], 
  [#strong[Interruptible];], [controls whether a running callback can be interrupted.], [Type: text scalar or character row vector. Supported values: 'on', 'off'.], 
  [#strong[LabelFontSizeMultiplier];], [recomputes geometry, limits, or layout.], [Type: finite numeric scalar. Supported values: finite scalar value.], 
  [#strong[Layer];], [controls whether axes grid lines and ticks are drawn behind or in front of plotted children.], [Type: text keyword. Supported values: 'bottom' or 'top'.], 
  [#strong[Layout];], [updates the object placement requested from the parent layout manager.], [Type: layout options object or empty value. Supported values: layout information stored by parent layout managers, including tile placement data where the object supports tiled layouts.], 
  [#strong[Legend];], [links the chart to the legend that represents it.], [Type: legend graphics object or empty handle value. Supported values: a legend object associated with the chart, or an empty graphics handle when no legend is attached.], 
  [#strong[LineStyleCyclingMethod];], [updates rendered output on the next graphics refresh.], [Type: text scalar or character row vector. Supported values: '-', '--', ':', '-.', 'none'.], 
  [#strong[LineStyleOrder];], [changes automatically selected line styles for subsequent plotted series.], [Type: text scalar, string array, or cell array of text. Supported values: '-', '--', ':', '-.', 'none'.], 
  [#strong[LineStyleOrderIndex];], [updates rendered output on the next graphics refresh.], [Type: text scalar or character row vector. Supported values: '-', '--', ':', '-.', 'none'.], 
  [#strong[LineWidth];], [updates rendered output on the next graphics refresh.], [Type: finite numeric scalar. Supported values: value greater than or equal to 0.], 
  [#strong[MinorGridAlpha];], [updates rendered output on the next graphics refresh.], [Type: numeric scalar or numeric array. Supported values: values in \[0,1\]; data arrays must match the related rendered data.], 
  [#strong[MinorGridAlphaMode];], ['auto' lets Nelson recompute the paired property; 'manual' preserves the assigned value.], [Type: text scalar or character row vector. Supported values: 'auto', 'manual'.], 
  [#strong[MinorGridColor];], [updates rendered output on the next graphics refresh.], [Type: color value. Supported values: 'red'\/'r', 'green'\/'g', 'blue'\/'b', 'cyan'\/'c', 'magenta'\/'m', 'yellow'\/'y', 'black'\/'k', 'white'\/'w', RGB triplet \[r g b\] with values in \[0,1\], or hexadecimal color '\#RRGGBB'\/'\#RGB'.], 
  [#strong[MinorGridColorMode];], ['auto' lets Nelson recompute the paired property; 'manual' preserves the assigned value.], [Type: text scalar or character row vector. Supported values: 'auto', 'manual'.], 
  [#strong[MinorGridLineStyle];], [updates rendered output on the next graphics refresh.], [Type: text scalar or character row vector. Supported values: '-', '--', ':', '-.', 'none'.], 
  [#strong[MinorGridLineWidth];], [updates rendered output on the next graphics refresh.], [Type: finite numeric scalar. Supported values: value greater than or equal to 0.], 
  [#strong[MinorGridLineWidthMode];], ['auto' lets Nelson recompute the paired property; 'manual' preserves the assigned value.], [Type: text scalar or character row vector. Supported values: 'auto', 'manual'.], 
  [#strong[NextPlot];], [selects how the next plotting command reuses or resets existing children.], [Type: text scalar or character row vector. Supported values: 'add', 'replace', 'replacechildren', 'replaceall', 'new'.], 
  [#strong[NextSeriesIndex];], [updates the stored object state.], [Type: integer scalar or numeric vector. Supported values: finite integer value, finite numeric value, or vector required by the property.], 
  [#strong[OuterPosition];], [recomputes geometry, limits, or layout.], [Type: finite numeric vector. Supported values: finite vector with the documented size, such as \[left bottom width height\], \[x y z\], \[azimuth elevation\], or \[minor major\].], 
  [#strong[Parent];], [reparents the object and updates Children on the old and new parents.], [Type: graphics object handle scalar. Supported values: a valid parent handle for the object class.], 
  [#strong[PickableParts];], [selects which visible or invisible parts can receive mouse hits.], [Type: text scalar or character row vector. Supported values: 'visible', 'all', 'none'.], 
  [#strong[PlotBoxAspectRatio];], [recomputes geometry, limits, or layout.], [Type: finite numeric vector. Supported values: finite vector with the documented size, such as \[left bottom width height\], \[x y z\], \[azimuth elevation\], or \[minor major\].], 
  [#strong[PlotBoxAspectRatioMode];], ['auto' lets Nelson recompute the paired property; 'manual' preserves the assigned value.], [Type: text scalar or character row vector. Supported values: 'auto', 'manual'.], 
  [#strong[Position];], [recomputes geometry, limits, or layout.], [Type: finite numeric vector. Supported values: finite vector with the documented size, such as \[left bottom width height\], \[x y z\], \[azimuth elevation\], or \[minor major\].], 
  [#strong[PositionConstraint];], [recomputes geometry, limits, or layout.], [Type: finite numeric vector. Supported values: finite vector with the documented size, such as \[left bottom width height\], \[x y z\], \[azimuth elevation\], or \[minor major\].], 
  [#strong[PositionMode];], ['auto' lets Nelson recompute the paired property; 'manual' preserves the assigned value.], [Type: text scalar or character row vector. Supported values: 'auto', 'manual'.], 
  [#strong[Projection];], [updates rendered output on the next graphics refresh.], [Type: text scalar or character row vector. Supported values: 'orthographic', 'perspective'.], 
  [#strong[RLim];], [updates radial axis limits and switches radial limit mode to manual when applicable.], [Type: two-element numeric vector. Supported values: finite increasing vector \[rmin rmax\].], 
  [#strong[RLimMode];], ['auto' lets Nelson recompute the paired property; 'manual' preserves the assigned value.], [Type: text scalar or character row vector. Supported values: 'auto', 'manual'.], 
  [#strong[RTick];], [recomputes geometry, limits, or layout.], [Type: finite numeric vector. Supported values: \[\] or a finite numeric vector, normally increasing.], 
  [#strong[RTickLabel];], [updates rendered output on the next graphics refresh.], [Type: text scalar, string array, or cell array of text. Supported values: empty text or labels matching the related ticks, categories, variables, lines, or displayed values.], 
  [#strong[RTickLabelMode];], ['auto' lets Nelson recompute the paired property; 'manual' preserves the assigned value.], [Type: text scalar or character row vector. Supported values: 'auto', 'manual'.], 
  [#strong[RTickMode];], ['auto' lets Nelson recompute the paired property; 'manual' preserves the assigned value.], [Type: text scalar or character row vector. Supported values: 'auto', 'manual'.], 
  [#strong[Selected];], [updates rendered output on the next graphics refresh.], [Type: text scalar or character row vector. Supported values: 'on', 'off'.], 
  [#strong[SelectionHighlight];], [updates rendered output on the next graphics refresh.], [Type: text scalar or character row vector. Supported values: 'on', 'off'.], 
  [#strong[SortMethod];], [updates rendered output on the next graphics refresh.], [Type: text scalar or character row vector. Supported values: 'childorder', 'depth'.], 
  [#strong[Subtitle];], [updates the displayed subtitle or subtitle object.], [Type: text graphics object or text value, depending on the object class. Supported values: a subtitle text object, character row vector, string scalar, or empty text.], 
  [#strong[SubtitleFontWeight];], [updates rendered output on the next graphics refresh.], [Type: text scalar or character row vector. Supported values: 'normal', 'bold'.], 
  [#strong[Tag];], [updates the stored object state.], [Type: text scalar or character row vector. Supported values: empty text or an object identifier.], 
  [#strong[TextHeight];], [recomputes geometry, limits, or layout.], [Type: finite numeric scalar. Supported values: finite scalar value.], 
  [#strong[ThetaAxis];], [exposes the numeric ruler that renders the theta axis.], [Type: NumericRuler object. Supported values: a scalar NumericRuler handle.], 
  [#strong[ThetaAxisUnits];], [sets angle units for theta limits, theta ticks, and theta tick labels.], [Type: text scalar or character row vector. Supported values: 'degrees', 'radians'.], 
  [#strong[ThetaLim];], [recomputes geometry, limits, or layout.], [Type: finite numeric vector. Supported values: two finite increasing values \[min max\].], 
  [#strong[ThetaLimMode];], ['auto' lets Nelson recompute the paired property; 'manual' preserves the assigned value.], [Type: text scalar or character row vector. Supported values: 'auto', 'manual'.], 
  [#strong[ThetaTick];], [recomputes geometry, limits, or layout.], [Type: finite numeric vector. Supported values: \[\] or a finite numeric vector, normally increasing.], 
  [#strong[ThetaTickLabel];], [updates rendered output on the next graphics refresh.], [Type: text scalar, string array, or cell array of text. Supported values: empty text or labels matching the related ticks, categories, variables, lines, or displayed values.], 
  [#strong[ThetaTickLabelMode];], ['auto' lets Nelson recompute the paired property; 'manual' preserves the assigned value.], [Type: text scalar or character row vector. Supported values: 'auto', 'manual'.], 
  [#strong[ThetaTickMode];], ['auto' lets Nelson recompute the paired property; 'manual' preserves the assigned value.], [Type: text scalar or character row vector. Supported values: 'auto', 'manual'.], 
  [#strong[TickDir];], [updates rendered output on the next graphics refresh.], [Type: text scalar or character row vector. Supported values: 'in', 'out', 'both', 'none'.], 
  [#strong[TickDirMode];], ['auto' lets Nelson recompute the paired property; 'manual' preserves the assigned value.], [Type: text scalar or character row vector. Supported values: 'auto', 'manual'.], 
  [#strong[TickLabelInterpreter];], [updates rendered output on the next graphics refresh.], [Type: text scalar, string array, or cell array of text. Supported values: empty text or labels matching the related ticks, categories, variables, lines, or displayed values.], 
  [#strong[TickLength];], [recomputes geometry, limits, or layout.], [Type: finite numeric vector. Supported values: finite vector with the documented size, such as \[left bottom width height\], \[x y z\], \[azimuth elevation\], or \[minor major\].], 
  [#strong[TightInset];], [recomputes geometry, limits, or layout.], [Type: finite numeric vector. Supported values: finite vector with the documented size, such as \[left bottom width height\], \[x y z\], \[azimuth elevation\], or \[minor major\].], 
  [#strong[Title];], [updates the displayed title or the title object associated with the graphics item.], [Type: text graphics object or text value, depending on the object class. Supported values: a title text object, character row vector, string scalar, or empty text.], 
  [#strong[TitleFontSizeMultiplier];], [recomputes geometry, limits, or layout.], [Type: finite numeric scalar. Supported values: finite scalar value.], 
  [#strong[TitleFontWeight];], [updates rendered output on the next graphics refresh.], [Type: text scalar or character row vector. Supported values: 'normal', 'bold'.], 
  [#strong[TitleHorizontalAlignment];], [updates rendered output on the next graphics refresh.], [Type: on\/off value. Supported values: 'on', 'off', true, or false.], 
  [#strong[Toolbar];], [updates rendered output on the next graphics refresh.], [Type: text scalar or character row vector. Supported values: 'none', 'figure', 'auto'.], 
  [#strong[Type];], [Nelson computes this value; graphics operations update it.], [Type: text scalar or character row vector. Supported values: read-only object type name, for example 'figure', 'axes', 'line', or 'scatter'.], 
  [#strong[Units];], [recomputes geometry, limits, or layout.], [Type: text scalar or character row vector. Supported values: 'pixels', 'normalized', 'inches', 'centimeters', 'points', 'characters', 'data'.], 
  [#strong[UserData];], [updates the stored object state.], [Type: Nelson array. Supported values: any Nelson value, including \[\], numeric arrays, text, cells, structures, or handles.], 
  [#strong[View];], [recomputes geometry, limits, or layout.], [Type: finite numeric vector. Supported values: finite vector with the documented size, such as \[left bottom width height\], \[x y z\], \[azimuth elevation\], or \[minor major\].], 
  [#strong[Visible];], [updates rendered output on the next graphics refresh.], [Type: text scalar or character row vector. Supported values: 'on', 'off'.], 
  [#strong[XAxis];], [exposes ruler state used for ticks, limits, scale, and labels.], [Type: axis ruler object. Supported values: an axis ruler object associated with the x direction.], 
  [#strong[XColorMode];], ['auto' lets Nelson recompute the paired property; 'manual' preserves the assigned value.], [Type: text scalar or character row vector. Supported values: 'auto', 'manual'.], 
  [#strong[XLimitMethod];], [selects how automatic x-axis limits are chosen.], [Type: text scalar or character row vector. Supported values: 'tickaligned', 'tight', 'padded'.], 
  [#strong[XMinorTick];], [recomputes geometry, limits, or layout.], [Type: finite numeric vector. Supported values: \[\] or a finite numeric vector, normally increasing.], 
  [#strong[XTickLabelRotation];], [updates rendered output on the next graphics refresh.], [Type: text scalar, string array, or cell array of text. Supported values: empty text or labels matching the related ticks, categories, variables, lines, or displayed values.], 
  [#strong[XTickLabelRotationMode];], ['auto' lets Nelson recompute the paired property; 'manual' preserves the assigned value.], [Type: text scalar or character row vector. Supported values: 'auto', 'manual'.], 
  [#strong[YAxis];], [exposes ruler state used for ticks, limits, scale, and labels.], [Type: axis ruler object. Supported values: an axis ruler object associated with the y direction.], 
  [#strong[YColorMode];], ['auto' lets Nelson recompute the paired property; 'manual' preserves the assigned value.], [Type: text scalar or character row vector. Supported values: 'auto', 'manual'.], 
  [#strong[YLimitMethod];], [selects how automatic y-axis limits are chosen.], [Type: text scalar or character row vector. Supported values: 'tickaligned', 'tight', 'padded'.], 
  [#strong[YMinorTick];], [recomputes geometry, limits, or layout.], [Type: finite numeric vector. Supported values: \[\] or a finite numeric vector, normally increasing.], 
  [#strong[YTickLabelRotation];], [updates rendered output on the next graphics refresh.], [Type: text scalar, string array, or cell array of text. Supported values: empty text or labels matching the related ticks, categories, variables, lines, or displayed values.], 
  [#strong[YTickLabelRotationMode];], ['auto' lets Nelson recompute the paired property; 'manual' preserves the assigned value.], [Type: text scalar or character row vector. Supported values: 'auto', 'manual'.], 
  [#strong[ZAxis];], [exposes ruler state used for ticks, limits, scale, and labels.], [Type: axis ruler object. Supported values: an axis ruler object associated with the z direction.], 
  [#strong[ZColorMode];], ['auto' lets Nelson recompute the paired property; 'manual' preserves the assigned value.], [Type: text scalar or character row vector. Supported values: 'auto', 'manual'.], 
  [#strong[ZLimitMethod];], [selects how automatic z-axis limits are chosen.], [Type: text scalar or character row vector. Supported values: 'tickaligned', 'tight', 'padded'.], 
  [#strong[ZMinorTick];], [recomputes geometry, limits, or layout.], [Type: finite numeric vector. Supported values: \[\] or a finite numeric vector, normally increasing.], 
  [#strong[ZTickLabelRotation];], [updates rendered output on the next graphics refresh.], [Type: text scalar, string array, or cell array of text. Supported values: empty text or labels matching the related ticks, categories, variables, lines, or displayed values.], 
  [#strong[ZTickLabelRotationMode];], ['auto' lets Nelson recompute the paired property; 'manual' preserves the assigned value.], [Type: text scalar or character row vector. Supported values: 'auto', 'manual'.], 
  [#strong[RAxis];], [exposes the numeric ruler that renders the r axis.], [Type: NumericRuler object. Supported values: a scalar NumericRuler handle.], 
  [#strong[RAxisLocation];], [positions the r-axis tick labels at the given angle.], [Type: finite numeric scalar. Supported values: finite scalar value.], 
  [#strong[RAxisLocationMode];], ['auto' lets Nelson recompute the paired property; 'manual' preserves the assigned value.], [Type: text scalar or character row vector. Supported values: 'auto', 'manual'.], 
  [#strong[RColor];], [updates rendered output on the next graphics refresh.], [Type: color value. Supported values: 'red'\/'r', 'green'\/'g', 'blue'\/'b', 'cyan'\/'c', 'magenta'\/'m', 'yellow'\/'y', 'black'\/'k', 'white'\/'w', RGB triplet \[r g b\] with values in \[0,1\], or hexadecimal color '\#RRGGBB'\/'\#RGB'.], 
  [#strong[RColorMode];], ['auto' lets Nelson recompute the paired property; 'manual' preserves the assigned value.], [Type: text scalar or character row vector. Supported values: 'auto', 'manual'.], 
  [#strong[RDir];], [updates rendered output on the next graphics refresh.], [Type: text scalar or character row vector. Supported values: 'normal', 'reverse'.], 
  [#strong[RGrid];], [shows or hides the radial grid lines.], [Type: on\/off value. Supported values: 'on', 'off', true, or false.], 
  [#strong[RMinorGrid];], [shows or hides the radial minor grid lines.], [Type: on\/off value. Supported values: 'on', 'off', true, or false.], 
  [#strong[RMinorTick];], [shows or hides the radial minor ticks.], [Type: on\/off value. Supported values: 'on', 'off', true, or false.], 
  [#strong[RTickLabelRotation];], [updates rendered output on the next graphics refresh.], [Type: finite numeric scalar. Supported values: finite scalar value.], 
  [#strong[RTickLabelRotationMode];], ['auto' lets Nelson recompute the paired property; 'manual' preserves the assigned value.], [Type: text scalar or character row vector. Supported values: 'auto', 'manual'.], 
  [#strong[ThetaColor];], [updates rendered output on the next graphics refresh.], [Type: color value. Supported values: 'red'\/'r', 'green'\/'g', 'blue'\/'b', 'cyan'\/'c', 'magenta'\/'m', 'yellow'\/'y', 'black'\/'k', 'white'\/'w', RGB triplet \[r g b\] with values in \[0,1\], or hexadecimal color '\#RRGGBB'\/'\#RGB'.], 
  [#strong[ThetaColorMode];], ['auto' lets Nelson recompute the paired property; 'manual' preserves the assigned value.], [Type: text scalar or character row vector. Supported values: 'auto', 'manual'.], 
  [#strong[ThetaDir];], [sets the direction of increasing theta angles.], [Type: text scalar or character row vector. Supported values: 'counterclockwise', 'clockwise'.], 
  [#strong[ThetaGrid];], [shows or hides the angular grid lines.], [Type: on\/off value. Supported values: 'on', 'off', true, or false.], 
  [#strong[ThetaMinorGrid];], [shows or hides the angular minor grid lines.], [Type: on\/off value. Supported values: 'on', 'off', true, or false.], 
  [#strong[ThetaMinorTick];], [shows or hides the angular minor ticks.], [Type: on\/off value. Supported values: 'on', 'off', true, or false.], 
  [#strong[ThetaZeroLocation];], [sets the location of the zero-degree reference direction.], [Type: text scalar or character row vector. Supported values: 'right', 'top', 'left', 'bottom'.], 
)

== Example

Create the graphics object and list its properties.

``````matlab
f = figure('Visible', 'off');
h = polaraxes('Parent', f);
names = properties(h);
close(f)
``````


== See also

#nlink(<graphics:1_plots.2_polar_plots.polaraxes>)[polaraxes];, #nlink(<handle:properties>)[properties];, #nlink(<handle:get>)[get];, #nlink(<handle:set>)[set];.

== History

#table(
  columns: 2,
  table.header([Version], [Description]),
  [--], [Property page added.],
)

// Author: Allan CORNET
