#import "nelson_help.typ": *

= pyrun <python_engine:pyrun>

Run Python statements from Nelson.

== Syntax

- #raw("pyrun(code)");
- #raw("outvars = pyrun(code, outputs)");
- #raw("outvars = pyrun(code, outputs, pyName, pyValue)");

== Input argument

/ code: a string scalar, string array, character vector, character array or python code object.
/ pyName, pyValue: Input arguments name and value
/ outputs: string array: Python variable names.

== Output argument

/ outvars: One or more Nelson workspace variable names returned as valid Python types.

== Description

#strong[pyrun(code)]; function executes Python statements present in the code string within the Python interpreter.

 Variables generated by the #strong[pyrun]; function remain persistent, allowing their usage in subsequent#strong[pyrun]; calls.

 #strong[outvars \= pyrun(code, outputs)]; Python variables specified in outputs are returned to Nelson.

 The values of these variables are captured in#strong[outvars];.

 #strong[outvars \= pyrun(code, outputs, pyName, pyValue)];, the #strong[code]; is executed with assigned input and output variable names using Nelson data passed through one or more name-value arguments.


== Examples

``````matlab
pyrun('a = b * c', 'b', 5, 'c', 10)
r = pyrun('d = a + c', 'd')
``````

``````matlab
pyrun(["a = 3","print(a)"])
``````

``````matlab
[R1, R2] = pyrun("a=b*c",["a","b"], 'b', 5, 'c', 10)
``````

Python code object representing a script generated through the built-in compile function in Python

``````matlab
PYCODE = pyrun('X = compile(''Y = 3'', ''test'', ''exec'')', 'X')
y = pyrun(PYCODE, 'Y')
``````


== See also

#nlink(<python_engine:pyrunfile>)[pyrunfile];, #nlink(<python_engine:pyfunction>)[pyfunction];, #nlink(<python_engine:pyenv>)[pyenv];, #nlink(<python_engine:3_python_types>)[Python types supported];.

== History

#table(
  columns: 2,
  table.header([Version], [Description]),
  [1.3.0], [initial version],
  [1.4.0], [Python code object allowed as first input argument],
)

// Author: Allan CORNET
