#import "../nelson_help.typ": *

= Changelog <main:CHANGELOG-0.6.x>


All notable changes to this project will be documented in this file.

The format is based on #link("https://keepachangelog.com/en/1.0.0/")[Keep a Changelog];.

== 0.6.12 (2022-12-27)


=== Added


Graphics module:

First big step to do plot 2D and 3D with Nelson. Some features are missing and will come in next releases.
Current version is usable and show plots possibilities of Nelson.

Do not hesitate to create features requests or bug reports. Contributions are welcome.

Implemented features:

- #raw("figure"); creates an figure window.
- #raw("cla"); clears figure.
- #raw("axes"); creates cartesian axes.
- #raw("axis"); set axis limits and aspect ratios.
- #raw("cla"); clears axes.
- #raw("zlim"); set or get z-axis limits.
- #raw("ylim"); set or get y-axis limits.
- #raw("xlim"); set or get x-axis limits.
- #raw("clim"); set colormap limits.
- #raw("line"); creates primitive line.
- #raw("plot"); 2-D line plot.
- #raw("plot3"); 3-D line plot.
- #raw("rgbplot"); Plot colormap.
- #raw("subplot"); Create axes in tiled positions.
- #raw("newplot"); Prepare to produce a new plot.
- #raw("semilogx"); Semilog plot (x-axis has log scale).
- #raw("semilogy"); Semilog plot (y-axis has log scale).s
- #raw("quiver"); Quiver or vector plot.
- #raw("surf"); creates surface plot.
- #raw("text"); creates text descriptions to data points.
- #raw("title"); adds title.
- #raw("legend"); adds legend to axes.
- #raw("xlabel"); Label x-axis.
- #raw("ylabel"); Label y-axis.
- #raw("zlabel"); Label z-axis.
- #raw("grid"); Display or hide axes grid lines.
- #raw("spy"); Visualize sparsity pattern of matrix.
- #raw("image"); displays image from array.
- #raw("imagesc"); displays image from array with scaled colors.
- #raw("cylinder"); creates cylinder.
- #raw("sphere"); creates sphere.
- #raw("close"); close one or more figures.
- #raw("gcf"); get current figure graphics object.
- #raw("gca"); get current axes graphics object.
- #raw("groot"); return graphic root object.
- #raw("refresh"); redraws current figure.
- #raw("ishold"); get current hold state.
- #raw("hold"); retain current plot when adding new plots.
- #raw("view"); Camera line of sigh.
- #raw("saveas"); Save figure to specific file format.
- #raw("copygraphics"); Copy plot to clipboard.
- #raw("isValidGraphicsProperty"); check property name is valid for a graphics object type name.
- #raw("isprop");, #raw("properties");, #raw("isequal");, #raw("eq");, #raw("display");, #raw("set");, #raw("get"); for Graphics Object type.
- #raw("isgraphics"); Check if it is an graphics object handles.
- #raw("colstyle"); Parse color and style from string.
- #raw("is2D"); Checks if ax is a 2-D Polar or Cartesian axes.
- #raw("colorbar"); Colorbar showing color scale.
- #raw("colormap"); View and set current colormap.
- colormaps:
  - #raw("autumn");: Autumn colormap array.
  - #raw("gray");: Gray colormap array.
  - #raw("parula");: Parula colormap array.
  - #raw("spring");: Spring colormap array.
  - #raw("summer");: Summer colormap array.
  - #raw("winter");: Winter colormap array.

``````markdown
░░ٌٌٌӇ░ٌٌٌƛ░ٌٌٌƤ░ٌٌٌƤ░ٌٌٌƳ ░ٌٌٌ░ٌٌٌƝ░ٌٌٌЄ░ٌٌٌƜ░ٌٌٌ░ٌٌٌ Ƴ░ٌٌٌЄ░ٌٌٌƛ░ٌٌٌƦ░ٌٌٌ!░
╚═════════ ೋღ❤ღೋ ═════════╝
``````


== 0.6.11 (2022-11-25)


=== Added


- #raw("normest"); 2-norm estimate.

- logical operators #raw("&");, #raw("|"); , #raw("&&");, #raw("||"); for sparses matrix managed.

- doxygen documentation generated by Github CI for each release.

- #raw("--noaudio"); CLI argument disable audio (module) in Nelson.

- #link("https://github.com/nelson-lang/nelson/issues/783")[\#783];: Fedora 37 support.

- an example to build mexFunction using Rust.

- geometry module:

  - #raw("rotx");: 3x3 transformation matrix for rotations around x-axis
  - #raw("roty");: 3x3 transformation matrix for rotations around y-axis
  - #raw("rotz");: 3x3 transformation matrix for rotations around z-axis

- #raw("spones"); replaces non zero sparse matrix elements with ones.

- #raw("rot90"); faster for 2D matrix.

=== Changed


- timeout #raw("--timeout"); CLI argument and #raw("system"); with timeout return error code #raw("258"); on Windows and #raw("134"); others platforms.

- #raw("test_run"); catches error code about test aborted (timeout).

- #raw("exit"); does not allow value \> 255 on Linux and MacOS.

- #link("https://github.com/nelson-lang/nelson/issues/776")[\#776];: internal dependencies between modules reworked.

- Uses MKL or OpenBlas if detected on linux and MacOs (Nelson is faster on Linux and MacOs).

=== Fixed


- basic terminal was closed immediately if stdin was null.

- Github Actions CI warnings.

- #link("https://github.com/nelson-lang/nelson/issues/778")[\#778];: ArchLinux Github CI was broken.

== 0.6.10 (2022-10-31)


=== Added


- #link("https://github.com/nelson-lang/nelson/issues/750")[\#750];: Qt 6.4.0 support (win64 release embed Qt6.4.0).

- #link("https://github.com/nelson-lang/nelson/issues/733")[\#733];: minimal build and optional installation on MacOs, Linux and Windows.

=== Fixed


- #link("https://github.com/nelson-lang/nelson/issues/762")[\#762];: MacOs CI was broken (libomp no more detected).

- #link("https://github.com/nelson-lang/nelson/issues/776")[\#776];: CodeQL Analyze was broken.

- #link("https://github.com/nelson-lang/nelson/issues/739")[\#739];: special case with empty cell.

- buildhelp did not return some errors.

=== Changed


- #link("https://github.com/nelson-lang/nelson/issues/755")[\#755];: Boost 1.80 support (default on Windows)

- #link("https://github.com/nelson-lang/nelson/issues/753")[\#753];: move from boost::filesystem to std::filesystem. (It should have no impact for users ...)

- Path functions returns sensitive path on Windows. #raw("cd ('c:/program files')"); returns true path #raw("C:/Program Files");.

- fileparts builtin updated to be more compatible.

- normalizePath internal function reworked.

- internal files functions reworked and factorized.

== 0.6.9 (2022-09-28)


=== Added


- linear algebra module:

  - #raw("rref");: Gauss-Jordan elimination.
  - #raw("orth");: Range space of a matrix.
  - #raw("subspace");: Angle between two subspaces.
  - #raw("planerot");: Givens plane rotation.
  - #raw("condeig");: Condition number with respect to eigenvalues.
  - #raw("bandwidth");: Lower and upper matrix bandwidth.
  - #raw("isbanded");: Determine if matrix is within specific bandwidth.

- audio module:

  - #raw("sound");: Convert matrix of signal data to sound and play it.
  - #raw("soundsc");: Scale data and play as sound.
  - #raw("mu2lin");: Convert audio data from mu-law to linear signal.
  - #raw("lin2mu");: Convert audio data from linear signal to mu-law.

- elementary functions module:

  - #raw("toeplitz");: Toeplitz matrix.
  - #raw("hadamard");: Hadamard matrix.
  - #raw("wilkinson");: Wilkinson's eigenvalue test matrix.
  - #raw("vander");: Vandermonde matrix.
  - #raw("rosser");: Classic symmetric eigenvalue test problem.
  - #raw("nextpow2");: Next higher power of 2.
  - #raw("permute");: Permute array dimensions.
  - #raw("ipermute");: Inverse permute array dimensions.
  - #raw("rot90");: Rotate array 90 degrees.

- special functions module:

  - #raw("dot");: Dot product.
  - #raw("cross");: Cross product.

- string module:

  - #raw("isletter");: Determine which characters are letters.

- data analysis module:

  - #raw("cumsum");: Cumulative sum.
  - #raw("cumprod");: Cumulative product.

=== Changed


- #link("https://github.com/nelson-lang/nelson/issues/715")[\#715];: update #raw("{fmt}"); to 9.1.0.

- Nelson uses #link("https://github.com/simdutf/simdutf")[#raw("simdutf");]; library to convert characters encoding faster.

- shortcuts #raw("&&"); and #raw("||"); reworked.

- assign behavior with empty matrix.

- #link("https://github.com/nelson-lang/nelson/issues/702")[\#702];: Ubuntu 18.04 CI removed on Github.

- Remove definitively Appveyor CI.

- C++ API: #raw("getContentAsDoubleScalar");, #raw("getContentAsSingleScalar");, #raw("getContentAsInteger8Scalar");, ... , #raw("getContentAsInteger64Scalar"); can check if it is an integer value.

- #raw("addgateway");, #raw("removegateway");, #raw("gatewayinfo"); builtin moved in #raw("modules_manager"); module (reduces dependency)

=== Fixed


- #link("https://github.com/nelson-lang/nelson/issues/722")[\#722];: MS MPI runtime v10.1.2.

- #link("https://github.com/nelson-lang/nelson/issues/723")[\#723];: MacOS CI was broken.

- #link("https://github.com/nelson-lang/nelson/issues/737")[\#737];: profiler failed with #raw("sind"); example.

- #link("https://github.com/nelson-lang/nelson/issues/739")[\#739];: special case with empty cell.

- #link("https://github.com/nelson-lang/nelson/issues/741")[\#741];: #raw("ones"); and #raw("zeros"); do not manager logical as typename.

== 0.6.8 (2022-08-27)


=== Added


- #link("https://github.com/nelson-lang/nelson/issues/574")[\#573];: #raw("diff"); differences and discret derivatives.

- #raw("peaks");: peaks function.

- parallel module:

  - #raw("fetchNext");: Retrieve next unread outputs from FevalFuture array.
  - #raw("afterAll");: Run function after all functions finish running in the background.
  - #raw("afterEach");: Run function after each functions finish running in the background.

- signal processing module:

  - #raw("hann");: Hann window.
  - #raw("hamming");: Hamming window.
  - #raw("bartlett");: Bartlett window.
  - #raw("blackman");: Blackman window.
  - #raw("sinc");: sinc function.
  - #raw("filter2");: 2-D digital filter.
  - #raw("fft2");: Two-dimensional discrete Fourier Transform.

- time functions:

  - #raw("weekday");: Day of week.
  - #raw("eomday");: Last day of month.
  - #raw("etime");: Time elapsed between date vectors.
  - #raw("date");: Current date as character vector.
  - #raw("timeit");: Measure time required to run function.
  - #raw("addtodate");: Modify date number by field.

- trigonometric functions:

  - #raw("rad2deg");: Convert angle from radians to degrees.
  - #raw("deg2rad");: Convert angle from degrees to radians.
  - #raw("cart2pol");: Transforms Cartesian coordinates to polar or cylindrical.
  - #raw("pol2cart");: Transforms polar or cylindrical coordinates to Cartesian.
  - #raw("cart2sph");: Transforms Cartesian to spherical coordinates.
  - #raw("sph2cart");: Transform spherical coordinates to Cartesian.
  - #raw("sech");: Hyperbolic secant.
  - #raw("secd");: Secant of argument in degrees.
  - #raw("sec");: Secant of angle in radians.
  - #raw("csch");: Hyperbolic cosecant.
  - #raw("cscd");: Cosecant of argument in degrees.
  - #raw("csc");: Cosecant of argument in radians.
  - #raw("coth");: Hyperbolic cotangent.
  - #raw("cot");: Cotangent of argument in radians.
  - #raw("cotd");: Cotangent of argument in degrees.
  - #raw("atand");: Inverse tangent in degrees.
  - #raw("atan2d");: Four-quadrant inverse tangent in degrees.
  - #raw("sinpi");: Computes sin(X \\\* pi) accurately.
  - #raw("cospi");: Computes cos(X \\\* pi) accurately.
  - #raw("asind");: Inverse sine in degrees.
  - #raw("asinh");: Inverse hyperbolic sine.
  - #raw("acosh");: Inverse hyperbolic cosine.
  - #raw("acosd");: Inverse cosine in degrees.
  - #raw("acoth");: Inverse hyperbolic cotangent.
  - #raw("acsc");: Inverse cosecant in radians.
  - #raw("acscd");: Inverse cosecant in degrees.
  - #raw("acsch");: Inverse hyperbolic cosecant.
  - #raw("asec");: Inverse secant in radians.
  - #raw("asecd");: Inverse secant in degrees.
  - #raw("asech");: Inverse hyperbolic secant.
  - #raw("acot");: Inverse cotangent in radians.
  - #raw("acotd");: Inverse cotangent in degrees.

- prettier is used to format .xml, .md files.

- Code format (.xml, .md, c++) checker added to Github CI.

=== Changed


- #raw("system"); builtin:

  - returns time execution
  - timeout input argument can be set to kill process after n seconds.

- #link("https://github.com/nelson-lang/nelson/issues/687")[\#687];: Uses BS thread pool 3.3.0.

- Windows 32 bits threads support: due to threading limitations with MKL, openMP and others threads
  computation threads are limited to 4 threads on Windows 32 bits.

- #link("https://github.com/nelson-lang/nelson/issues/683")[\#683];: MacOS Catalina removed on Github CI (no more officially supported).

- Help chapter titles all start with a capital letter.

- #link("https://github.com/nelson-lang/nelson/issues/771")[\#771];: Fedora 36 Github CI replaces Fedora 35 Github CI.

=== Fixed


- #link("https://github.com/nelson-lang/nelson/issues/689")[\#689];: #raw("c = computer"); returns an error.
- #link("https://github.com/nelson-lang/nelson/issues/691")[\#691];: help generation crashes if copyright tag is empty.
- #link("https://github.com/nelson-lang/nelson/issues/35")[\#35];: datenum does not support vectorization.
- #raw("or");, #raw("and"); do not manage matrix operator scalar case.

== 0.6.7 (2022-07-27)


=== Added


- #raw("str2func"); manages anonymous function.

- Parallel functions (part 2):

  - #raw("cancelAll");: Stop all functions running in the background.
  - #raw("cancel");: Stop function running in the background.
  - #raw("wait");: Wait for futures to be completed.
  - #raw("Diary"); property for #raw("FevalFuture"); object.

- CITATION.cff with human- and machine-readable citation information for software.

=== Changed


- localization files #raw(".pot");, #raw(".po"); updated.

=== Fixed


- #link("https://github.com/nelson-lang/nelson/issues/679")[\#679];: uniformize path for includes and libraries.

== 0.6.6 (2022-06-27)


=== Added


- Parallel functions (part 1):

  - #raw("parfeval");: Run function on parallel background thread pool worker.
  - #raw("backgroundPool");: Environment for running code in the background.
  - #raw("fetchOutputs");: Retrieve results from function running in the background.

- #link("https://github.com/nelson-lang/nelson/issues/666")[\#666];: #raw("ls"); function: List folder contents.

- #link("https://github.com/nelson-lang/nelson/issues/655")[\#655];: help viewer embedded (available on all platforms).

=== Changed


- LGTM replaced by CodeQL (Thanks to Github for their support)

- #link("https://github.com/nelson-lang/nelson/issues/662")[\#662];: Snap uses Core22 and Qt6 (all dependencies are up-to-date).

- #link("https://github.com/nelson-lang/nelson/issues/668")[\#668];: #raw("maxNumCompThreads"); detects numbers of physical cores on Windows.

- matrix of handles supported.

- #link("https://github.com/nelson-lang/nelson/issues/676")[\#676];: use fmtlib 9.0

=== Fixed


- #link("https://github.com/nelson-lang/nelson/issues/659")[\#659];: qhelpgenerator on macOs after brew Qt6.3.0 update.

- #link("https://github.com/nelson-lang/nelson/issues/661")[\#661];: CodeQL warnings.

== 0.6.5 (2022-05-26)


=== Added


- #link("https://github.com/nelson-lang/nelson/issues/572")[\#572];: #raw("pow2");: Base 2 exponentiation.

- #raw("audioread");, #raw("audiowrite"); supports new file formats #raw(".mp3");, #raw(".flac");, #raw(".caf"); (Thanks to libsndfile).

- MacOs 12 Monterey Github CI.

- #link("https://github.com/nelson-lang/nelson/issues/634")[\#634];: Ubuntu 22.04 CI.

=== Changed


- #link("https://github.com/nelson-lang/nelson/issues/631")[\#631];: Qt6 used as default distribution on some OS platforms.

  For backport compatibility only Qt5.15.x and Qt6.3 (or more) are supported.

  - Windows 64 bits: Qt6.3
  - Windows 32 bits: Qt5.15.x
  - Ubuntu 22.04: Qt6.3
  - Ubuntu 20.04, 18.04: Qt5.15.x
  - MacOs Monterey: Qt6.3
  - MacOs BigSur, Catalina: Qt5.15.x
  - Others OS platforms: Qt version based on distributed Qt version.

- #link("https://github.com/nelson-lang/nelson/issues/636")[\#636];: docker image uses bullseye image.

- #raw("system"); builtin: multithread rework.

- #link("https://github.com/nelson-lang/nelson/issues/633")[\#633];: libsndfile 1.1.0 used.

- Windows build uses #raw("/permissive-"); option.

- #link("https://github.com/nelson-lang/nelson/issues/646")[\#646];: #raw("warndlg");, #raw("questdlg");, #raw("errordlg");, #raw("helpdlg"); reworked to better Qt6 support.

=== Fixed


- Dark theme detection with Gnome.

- #link("https://github.com/nelson-lang/nelson/issues/642")[\#642];: #raw("rand"); was not thread safe.

- #link("https://github.com/nelson-lang/nelson/issues/648")[\#648];: Ubuntu 18.04 CI failed.

- #link("https://github.com/nelson-lang/nelson/issues/651")[\#651];: MacOs monterey crashes at exit with mpi module.

== 0.6.4 (2022-04-24)


=== Changed


- #link("https://github.com/nelson-lang/nelson/issues/590")[\#590];: Nelson's license moved to LGPL v3.0 and GPL v3.0 and uses SPDX format.

- Nelson uses #link("https://sourcefoundry.org/hack/")[Hack]; font.

- Linux 64 bits and 32 bits uses same main script.

- #link("https://github.com/nelson-lang/nelson/issues/594")[\#594];: #raw(".pot"); used to generate en\_US.

=== Added


- 'sscanf' reworked to manage unicode characters and speed optimization.

- French translations imported from Weblate (Thanks to contributors)

- Dark theme detected and applied on Linux, MacOS and Windows.

- #link("https://github.com/nelson-lang/nelson/issues/559")[\#559];: #raw("formattedDisplayText"); function: Capture display output as string.

- Better detection Qt6 or Qt5 with CMake.

=== Fixed


- Main Nelson's font was not applied on some OS platforms (ex: MacOS Catalina)

- #link("https://github.com/nelson-lang/nelson/issues/622")[\#622];: #raw("isreal(sqrt(i^4))"); did not return true.

- Nelson's help indexing is faster (x100).

== 0.6.3 (2022-03-26)


=== Changed


- #link("https://github.com/nelson-lang/nelson/issues/596")[\#596];: Tests results display use emoji if terminal supports Unicode.

=== Added


- Packaging:

  - #link("https://github.com/nelson-lang/nelson/issues/603")[\#603];: Nelson as snap package for Linux.
  - #link("https://github.com/nelson-lang/nelson/issues/605")[\#605];: \[Package request\] Chocolatey package manager for Windows.
  - #link("https://github.com/nelson-lang/nelson/issues/582")[\#582];: Nelson available as Portable apps.

- add information for Software Center (Linux desktop, icons).

- #raw("nelson"); Main script to start Nelson (supersede others scripts).

- #raw("isunicodesupported"); function: Detect whether the current terminal supports Unicode.

- #raw("dlsym"); function: search nearest symbol name if value entry is not found.

- #raw("terminal_size"); function:Query the size of the terminal window.

- #link("https://github.com/nelson-lang/nelson/issues/598")[\#598];: #raw("sscanf"); function read formatted data from strings.

=== Fixed


- #link("https://github.com/nelson-lang/nelson/issues/599")[\#599];: #raw("make install"); step in CI for linux and MacOs.

- #link("https://github.com/nelson-lang/nelson/issues/601")[\#601];: embed all tests on linux and macos install.

== 0.6.2 (2022-02-26)


=== Changed


- #link("https://github.com/nelson-lang/nelson/issues/576")[\#576];: C++17 Compiler required to build Nelson.

- #link("https://github.com/nelson-lang/nelson/issues/581")[\#581];: Github CI platforms list extended (ArchLinux, Fedora, Ubuntu 18.04, MacOs BigSur).

- #link("https://github.com/nelson-lang/nelson/issues/539")[\#539];: Visual studio 2022 build on Windows

  - Visual studio 2022 solution upgraded,
  - Github CI and Appveyor use VS 2022 image,
  - boost 1.78 (VS 2022 x86, x64 build),
  - Eigen 3.4 stable branch (Feb 06/22),
  - MSVC 2022 support added to build C/C++ code easily "on fly" on Windows,
  - slicot 5.0 (VS 2022 x86, x64 build),
  - libffi (VS 2022 x86, x64 build),
  - taglib 1.12 (VS 2022 x86, x64 build),
  - hdf5 1.12.1 (VS 2022 x86, x64 build),
  - matio 1.5.21 (VS 2022 x86, x64 build),
  - all others windows dependencies rebuilt with VS 2022.
  - #link("https://github.com/nelson-lang/nelson/issues/505")[\#505];: libCurl 7.81 on Windows.
  - #link("https://github.com/nelson-lang/nelson/issues/524")[\#524];: oneApi 2022.1 on Windows.

=== Added


- Nelson uses #raw("JuliaMono-Regular"); font as default.
- #link("https://github.com/nelson-lang/nelson/issues/567")[\#567];: #raw("..."); in cells if character vector is too long.

=== Fixed


- #link("https://github.com/nelson-lang/nelson/issues/587")[\#587];: implicit cast to string array for horzcat and vertcat operators.
- #link("https://github.com/nelson-lang/nelson/issues/562")[\#562];: #raw("format long"); complex do not display expected precision.
- scale factor for integer values did not display as expected.
- #link("https://github.com/nelson-lang/nelson/issues/561")[\#561];: #raw("0^0"); did not return expected value.
- #link("https://github.com/nelson-lang/nelson/issues/560")[\#560];: many warnings fixed (Thanks to new PVS-Studio and cppcheck).
- cmake #raw("WITH_SLICOT");, #raw("WITH_FFTW");, #raw("ENABLE_CLANG_TIDY_FIX"); were not documented.
- #link("https://github.com/nelson-lang/nelson/issues/584")[\#584];: docker files updated to support C++17 and new libraries.
- #link("https://github.com/nelson-lang/nelson/issues/591")[\#591];: Innosetup display glitch with #raw("Nelson's website"); button.

== 0.6.1 (2022-01-31)


=== Changed


- display of all types reworked to be #raw("pixel perfect");. (a small sentence but a big rework)

=== Added


- #raw("format"); extended to manage: #raw("compact");, #raw("loose");, #raw("longE");, #raw("longG");, #raw("hex");, #raw("bank");, #raw("rational");.
- #link("https://github.com/nelson-lang/nelson/issues/507")[\#507];: #raw("celldisp");: Display cell array contents.
- #link("https://github.com/nelson-lang/nelson/issues/548")[\#548];: #raw("hypot"); builtin: Square root of sum of squares.
- #link("https://github.com/nelson-lang/nelson/issues/555")[\#555];: #raw("rsf2csf"); function: Convert real Schur form to complex Schur form.
- #raw("CHANGELOG"); 0.6.x family.

== Previous changelog


#nlink(<main:CHANGELOG-0.5.x>)[Changelog v0.5.x];

#nlink(<main:CHANGELOG-0.4.x>)[Changelog v0.4.x];

#nlink(<main:CHANGELOG-0.3.x>)[Changelog v0.3.x];

#nlink(<main:CHANGELOG-0.2.x>)[Changelog v0.2.x];

#nlink(<main:CHANGELOG-0.1.x>)[Changelog v0.1.x];
