//=============================================================================
// Copyright (c) 2026-present Allan CORNET (Nelson)
//=============================================================================
// This file is part of Nelson.
//=============================================================================
// LICENCE_BLOCK_BEGIN
// SPDX-License-Identifier: LGPL-3.0-or-later
// LICENCE_BLOCK_END
//=============================================================================
use std::env;
use std::path::{Path, PathBuf};

use anyhow::{bail, Context, Result};
use clap::Parser;

#[derive(Debug, Parser)]
#[command(
    author,
    version,
    about = "Build the Nelson PDF manuals from the Typst sources generated by buildhelptypst"
)]
pub struct Cli {
    /// Languages to build, e.g. en,fr: compiles typst/<lang>/main.typ into
    /// nelson-<lang>.pdf in the current directory.
    #[arg(long, value_delimiter = ',')]
    pub languages: Vec<String>,

    /// Compile a single Typst document instead of the per-language layout.
    #[arg(long = "typst-main")]
    pub typst_main: Option<PathBuf>,

    /// Output PDF for --typst-main (default: next to the main file).
    #[arg(long = "output-file")]
    pub output_file: Option<PathBuf>,

    #[arg(long)]
    pub verbose: bool,
}

impl Cli {
    pub fn parse_args() -> Self {
        Self::parse()
    }
}

#[derive(Debug, Clone)]
pub struct Config {
    pub mode: BuildMode,
    pub verbose: bool,
}

#[derive(Debug, Clone)]
pub enum BuildMode {
    Single {
        main_typ: PathBuf,
        output_file: PathBuf,
    },
    Languages {
        root_dir: PathBuf,
        languages: Vec<String>,
    },
}

impl Config {
    pub fn from_cli(cli: Cli) -> Result<Self> {
        let cwd = env::current_dir().context("failed to read current directory")?;
        let mode = build_mode_from_cli(&cli, &cwd)?;
        Ok(Self {
            mode,
            verbose: cli.verbose,
        })
    }
}

fn build_mode_from_cli(cli: &Cli, cwd: &Path) -> Result<BuildMode> {
    if !cli.languages.is_empty() {
        if cli.typst_main.is_some() || cli.output_file.is_some() {
            bail!("--languages cannot be combined with --typst-main or --output-file");
        }
        return Ok(BuildMode::Languages {
            root_dir: cwd.to_path_buf(),
            languages: cli.languages.clone(),
        });
    }

    let main_typ = cli
        .typst_main
        .as_ref()
        .context("--typst-main is required unless --languages is used")
        .map(|path| absolute_path(path, cwd))?;
    if !main_typ.is_file() {
        bail!("Typst main file not found: {}", main_typ.display());
    }
    let output_file = match &cli.output_file {
        Some(path) => absolute_path(path, cwd),
        None => main_typ.with_extension("pdf"),
    };

    Ok(BuildMode::Single {
        main_typ,
        output_file,
    })
}

fn absolute_path(path: &Path, cwd: &Path) -> PathBuf {
    let joined = if path.is_absolute() {
        path.to_path_buf()
    } else {
        cwd.join(path)
    };
    normalize_lexically(joined)
}

pub fn normalize_lexically(path: PathBuf) -> PathBuf {
    let mut out = PathBuf::new();
    for component in path.components() {
        match component {
            std::path::Component::CurDir => {}
            std::path::Component::ParentDir => {
                out.pop();
            }
            other => out.push(other.as_os_str()),
        }
    }
    out
}

#[derive(Debug, Clone, Copy)]
pub struct Logger {
    verbose: bool,
}

impl Logger {
    pub fn new(verbose: bool) -> Self {
        Self { verbose }
    }

    pub fn info(&self, message: impl AsRef<str>) {
        println!("{}", message.as_ref());
    }

    pub fn verbose(&self, message: impl AsRef<str>) {
        if self.verbose {
            println!("{}", message.as_ref());
        }
    }

    pub fn is_verbose(&self) -> bool {
        self.verbose
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::tempdir;

    #[test]
    fn normalize_removes_current_and_parent_components() {
        // Built with join so that the separators are the platform's own:
        // a backslash is a plain character on Linux, not a separator.
        let path = normalize_lexically(
            PathBuf::from("root")
                .join("a")
                .join(".")
                .join("b")
                .join("..")
                .join("c"),
        );
        assert_eq!(path, PathBuf::from("root").join("a").join("c"));
    }

    #[cfg(windows)]
    #[test]
    fn normalize_keeps_the_drive_prefix() {
        let path = normalize_lexically(PathBuf::from(r"C:\a\.\b\..\c"));
        assert_eq!(path.to_string_lossy(), r"C:\a\c");
    }

    #[test]
    fn language_mode_rejects_single_build_options() {
        let cli = Cli {
            typst_main: Some(PathBuf::from("typst/en/main.typ")),
            output_file: None,
            languages: vec!["en".to_string()],
            verbose: false,
        };
        let err = build_mode_from_cli(&cli, Path::new(".")).unwrap_err();
        assert!(err.to_string().contains("cannot be combined"));
    }

    #[test]
    fn single_mode_defaults_output_next_to_main() -> Result<()> {
        let dir = tempdir()?;
        let main = dir.path().join("main.typ");
        fs::write(&main, "")?;
        let cli = Cli {
            typst_main: Some(main.clone()),
            output_file: None,
            languages: vec![],
            verbose: true,
        };

        let config = Config::from_cli(cli)?;

        match config.mode {
            BuildMode::Single {
                main_typ,
                output_file,
            } => {
                assert_eq!(main_typ, main);
                assert_eq!(output_file, dir.path().join("main.pdf"));
            }
            BuildMode::Languages { .. } => panic!("unexpected language mode"),
        }
        assert!(config.verbose);
        Ok(())
    }

    #[test]
    fn single_mode_requires_typst_main() {
        let cli = Cli {
            typst_main: None,
            output_file: Some(PathBuf::from("out.pdf")),
            languages: vec![],
            verbose: false,
        };
        let err = build_mode_from_cli(&cli, Path::new(".")).unwrap_err();
        assert!(err.to_string().contains("--typst-main is required"));
    }
}
