//=============================================================================
// Copyright (c) 2026-present Allan CORNET (Nelson)
//=============================================================================
// This file is part of Nelson.
//=============================================================================
// LICENCE_BLOCK_BEGIN
// SPDX-License-Identifier: LGPL-3.0-or-later
// LICENCE_BLOCK_END
//=============================================================================
//! In-process Typst compilation of the help sources generated by Nelson's
//! `buildhelptypst` (one `main.typ` per language under `typst/<lang>/`).
//!
//! No external executable is involved: the Typst compiler, its embedded fonts
//! and the PDF exporter are linked into the builder.
use std::fs;
use std::io::Cursor;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicUsize, Ordering};
use std::time::Instant;

use base64::Engine as _;

use anyhow::{bail, Context, Result};
use typst::diag::{FileError, FileResult, PackageError, Severity, SourceDiagnostic, Warned};
use typst::foundations::{Bytes, Datetime, Duration, Smart};
use typst::syntax::{FileId, RootedPath, Source, VirtualPath, VirtualRoot};
use typst::text::{Font, FontBook};
use typst::utils::LazyHash;
use typst::{Library, LibraryExt, World, WorldExt};
use typst_kit::files::{FileLoader, FileStore, FsRoot};
use typst_kit::fonts::{self, FontStore};
use typst_layout::PagedDocument;
use typst_pdf::Timestamp;

use crate::config::Logger;

/// Directory (relative to the current directory) where additional fonts can be
/// dropped, for example a color emoji font.
pub const FONTS_DIR: &str = "theme/fonts";

/// Directory (relative to the current directory) holding vendored Typst
/// packages, laid out as `<namespace>/<name>/<version>/`.
pub const PACKAGES_DIR: &str = "theme/typst-packages";

/// Maximum width (in pixels) kept for bitmaps: PNG figures and the bitmaps
/// embedded in SVG figures.
///
/// Nelson exports some 3D plots as SVG files carrying several full-canvas
/// PNG layers of about 1700 px: 138 such figures weigh 925 MB once decoded
/// and made the English manual a 157 MB PDF. Screenshots and image-processing
/// results are PNG files of 1000 to 1700 px. Downscaling the bitmaps (vector
/// parts are untouched) keeps print quality at A4 size: 800 px over the
/// 178 mm text width is about 115 dpi.
pub const MAX_EMBEDDED_BITMAP_WIDTH: u32 = 800;

/// Loads project files from the directory of `main.typ`, and packages from the
/// vendored packages directory (no network access).
struct ProjectLoader {
    project: FsRoot,
    packages: Option<PathBuf>,
    /// Number of SVG files whose embedded bitmaps were downscaled, and the
    /// bytes saved on their base64 payload.
    svg_downscaled: AtomicUsize,
    svg_bytes_saved: AtomicUsize,
    /// Number of PNG files downscaled, and the bytes saved on their encoding.
    png_downscaled: AtomicUsize,
    png_bytes_saved: AtomicUsize,
}

impl FileLoader for ProjectLoader {
    fn load(&self, id: FileId) -> FileResult<Bytes> {
        match id.root() {
            VirtualRoot::Project => {
                let bytes = self.project.load(id.vpath())?;
                let name = id.vpath().get_without_slash().to_ascii_lowercase();
                if name.ends_with(".png") {
                    return Ok(
                        match downscale_png(bytes.as_slice(), MAX_EMBEDDED_BITMAP_WIDTH) {
                            Some(smaller) => {
                                self.png_downscaled.fetch_add(1, Ordering::Relaxed);
                                self.png_bytes_saved.fetch_add(
                                    bytes.len().saturating_sub(smaller.len()),
                                    Ordering::Relaxed,
                                );
                                Bytes::new(smaller)
                            }
                            None => bytes,
                        },
                    );
                }
                if !name.ends_with(".svg") {
                    return Ok(bytes);
                }
                let Ok(text) = std::str::from_utf8(bytes.as_slice()) else {
                    return Ok(bytes);
                };
                match downscale_svg_bitmaps(text, MAX_EMBEDDED_BITMAP_WIDTH) {
                    Some(smaller) => {
                        self.svg_downscaled.fetch_add(1, Ordering::Relaxed);
                        self.svg_bytes_saved
                            .fetch_add(text.len().saturating_sub(smaller.len()), Ordering::Relaxed);
                        Ok(Bytes::from_string(smaller))
                    }
                    None => Ok(bytes),
                }
            }
            VirtualRoot::Package(spec) => {
                let Some(packages) = &self.packages else {
                    return Err(FileError::Package(PackageError::NotFound(spec.clone())));
                };
                let dir = packages
                    .join(spec.namespace.as_str())
                    .join(spec.name.as_str())
                    .join(spec.version.to_string());
                if !dir.is_dir() {
                    return Err(FileError::Package(PackageError::NotFound(spec.clone())));
                }
                FsRoot::new(dir).load(id.vpath())
            }
        }
    }
}

pub struct NelsonWorld {
    library: LazyHash<Library>,
    fonts: FontStore,
    files: FileStore<ProjectLoader>,
    main: FileId,
}

impl NelsonWorld {
    pub fn new(main_typ: &Path, logger: Logger) -> Result<Self> {
        let main_typ = main_typ
            .canonicalize()
            .with_context(|| format!("Typst main file not found: {}", main_typ.display()))?;
        let root = main_typ
            .parent()
            .context("Typst main file has no parent directory")?
            .to_path_buf();
        let file_name = main_typ
            .file_name()
            .and_then(|name| name.to_str())
            .context("Typst main file has no valid name")?;
        let vpath = VirtualPath::new(file_name)
            .with_context(|| format!("invalid Typst path: {file_name}"))?;
        let main = RootedPath::new(VirtualRoot::Project, vpath).intern();

        let cwd = std::env::current_dir().context("failed to read current directory")?;
        let packages = cwd.join(PACKAGES_DIR);
        let packages = packages.is_dir().then_some(packages);

        let started = Instant::now();
        let mut fonts = FontStore::new();
        let embedded: Vec<_> = fonts::embedded().collect();
        let embedded_count = embedded.len();
        fonts.extend(embedded);
        let mut extra_count = 0;
        let extra_fonts = cwd.join(FONTS_DIR);
        if extra_fonts.is_dir() {
            let extra: Vec<_> = fonts::scan(&extra_fonts).collect();
            extra_count = extra.len();
            fonts.extend(extra);
        }
        let system: Vec<_> = fonts::system().collect();
        let system_count = system.len();
        fonts.extend(system);
        logger.info(format!(
            "Fonts: {embedded_count} embedded, {extra_count} from {FONTS_DIR}, {system_count} system ({:.1}s)",
            started.elapsed().as_secs_f64()
        ));

        Ok(Self {
            library: LazyHash::new(Library::default()),
            fonts,
            files: FileStore::new(ProjectLoader {
                project: FsRoot::new(root),
                packages,
                svg_downscaled: AtomicUsize::new(0),
                svg_bytes_saved: AtomicUsize::new(0),
                png_downscaled: AtomicUsize::new(0),
                png_bytes_saved: AtomicUsize::new(0),
            }),
            main,
        })
    }
}

impl NelsonWorld {
    fn report_downscaling(&self, logger: Logger) {
        let loader = self.files.loader();
        let count = loader.svg_downscaled.load(Ordering::Relaxed);
        if count > 0 {
            logger.info(format!(
                "Downscaled embedded bitmaps in {count} SVG figure(s) to at most {MAX_EMBEDDED_BITMAP_WIDTH} px wide ({:.1} MB of base64 saved)",
                loader.svg_bytes_saved.load(Ordering::Relaxed) as f64 / 1e6
            ));
        }
        let count = loader.png_downscaled.load(Ordering::Relaxed);
        if count > 0 {
            logger.info(format!(
                "Downscaled {count} PNG figure(s) to at most {MAX_EMBEDDED_BITMAP_WIDTH} px wide ({:.1} MB saved)",
                loader.png_bytes_saved.load(Ordering::Relaxed) as f64 / 1e6
            ));
        }
    }
}

/// Current local time, or UTC when the local offset cannot be determined
/// (for example on Linux once the process is multi-threaded).
fn now_local() -> time::OffsetDateTime {
    time::OffsetDateTime::now_local().unwrap_or_else(|_| time::OffsetDateTime::now_utc())
}

/// Creation timestamp written in the PDF metadata (`set document(date: ..)`
/// stays `auto` in the generated sources).
fn creation_timestamp() -> Option<Timestamp> {
    let now = now_local();
    let datetime = Datetime::from_ymd_hms(
        now.year(),
        now.month() as u8,
        now.day(),
        now.hour(),
        now.minute(),
        now.second(),
    )?;
    Timestamp::new_local(datetime, i32::from(now.offset().whole_minutes()))
        .or_else(|| Some(Timestamp::new_utc(datetime)))
}

/// Rewrites `data:image/png;base64,...` payloads of an SVG so that no embedded
/// bitmap is wider than `max_width`. Returns `None` when nothing changed.
pub fn downscale_svg_bitmaps(svg: &str, max_width: u32) -> Option<String> {
    const PREFIX: &str = "data:image/png;base64,";
    if !svg.contains(PREFIX) {
        return None;
    }
    let engine = base64::engine::general_purpose::STANDARD;
    let mut out = String::with_capacity(svg.len());
    let mut rest = svg;
    let mut changed = false;
    while let Some(start) = rest.find(PREFIX) {
        let payload_start = start + PREFIX.len();
        let payload_len = rest[payload_start..]
            .find(|c: char| !(c.is_ascii_alphanumeric() || c == '+' || c == '/' || c == '='))
            .unwrap_or(rest.len() - payload_start);
        let payload = &rest[payload_start..payload_start + payload_len];
        out.push_str(&rest[..payload_start]);
        match engine
            .decode(payload)
            .ok()
            .and_then(|png| downscale_png(&png, max_width))
        {
            Some(smaller) => {
                out.push_str(&engine.encode(smaller));
                changed = true;
            }
            None => out.push_str(payload),
        }
        rest = &rest[payload_start + payload_len..];
    }
    out.push_str(rest);
    changed.then_some(out)
}

fn downscale_png(png: &[u8], max_width: u32) -> Option<Vec<u8>> {
    let image = image::load_from_memory_with_format(png, image::ImageFormat::Png).ok()?;
    if image.width() <= max_width {
        return None;
    }
    let height =
        (u64::from(image.height()) * u64::from(max_width) / u64::from(image.width())).max(1) as u32;
    let resized = image.resize_exact(max_width, height, image::imageops::FilterType::Triangle);
    let mut buffer = Cursor::new(Vec::new());
    resized
        .write_to(&mut buffer, image::ImageFormat::Png)
        .ok()?;
    Some(buffer.into_inner())
}

impl World for NelsonWorld {
    fn library(&self) -> &LazyHash<Library> {
        &self.library
    }

    fn book(&self) -> &LazyHash<FontBook> {
        self.fonts.book()
    }

    fn main(&self) -> FileId {
        self.main
    }

    fn source(&self, id: FileId) -> FileResult<Source> {
        self.files.source(id)
    }

    fn file(&self, id: FileId) -> FileResult<Bytes> {
        self.files.file(id)
    }

    fn font(&self, index: usize) -> Option<Font> {
        self.fonts.font(index)
    }

    /// Date for `datetime.today()`: local date, or the date at the given UTC
    /// offset (same convention as the typst CLI).
    fn today(&self, offset: Option<Duration>) -> Option<Datetime> {
        let now = match offset {
            None => now_local(),
            Some(offset) => {
                let seconds = i32::try_from(offset.seconds() as i64).ok()?;
                time::OffsetDateTime::now_utc()
                    .to_offset(time::UtcOffset::from_whole_seconds(seconds).ok()?)
            }
        };
        Datetime::from_ymd(now.year(), now.month() as u8, now.day())
    }
}

#[derive(Debug, Clone, Copy)]
pub struct CompileStats {
    pub pages: usize,
    pub warnings: usize,
}

/// Compiles `main_typ` and writes the PDF to `output_pdf`.
pub fn compile_pdf(main_typ: &Path, output_pdf: &Path, logger: Logger) -> Result<CompileStats> {
    let world = NelsonWorld::new(main_typ, logger)?;

    logger.info(format!("Compiling {} with Typst...", main_typ.display()));
    let started = Instant::now();
    let Warned { output, warnings } = typst::compile::<PagedDocument>(&world);
    report_diagnostics(&world, &warnings, logger);
    let document = match output {
        Ok(document) => document,
        Err(errors) => {
            report_diagnostics(&world, &errors, logger);
            bail!(
                "Typst compilation failed with {} error(s) (see messages above)",
                errors.len()
            );
        }
    };
    logger.info(format!(
        "Typst layout done: {} pages in {:.1}s",
        document.pages().len(),
        started.elapsed().as_secs_f64()
    ));
    world.report_downscaling(logger);

    let export_started = Instant::now();
    // The tagged-PDF structure tree (one StructElem per paragraph, link and
    // table cell) weighed ~100 MB of the 150 MB English manual; the manual is
    // not produced as PDF/UA, so tagging is disabled.
    let options = typst_pdf::PdfOptions {
        tagged: false,
        timestamp: creation_timestamp(),
        creator: Smart::Custom(Some(format!(
            "nelson-pdf-builder {}",
            env!("CARGO_PKG_VERSION")
        ))),
        ..Default::default()
    };
    let pdf = match typst_pdf::pdf(&document, &options) {
        Ok(pdf) => pdf,
        Err(errors) => {
            report_diagnostics(&world, &errors, logger);
            bail!("PDF export failed with {} error(s)", errors.len());
        }
    };
    fs::write(output_pdf, &pdf)
        .with_context(|| format!("failed to write {}", output_pdf.display()))?;
    logger.info(format!(
        "PDF exported: {} bytes in {:.1}s",
        pdf.len(),
        export_started.elapsed().as_secs_f64()
    ));

    Ok(CompileStats {
        pages: document.pages().len(),
        warnings: warnings.len(),
    })
}

/// Prints diagnostics with their file and line, deduplicated and capped so a
/// systematic warning does not flood the log.
fn report_diagnostics(world: &NelsonWorld, diagnostics: &[SourceDiagnostic], logger: Logger) {
    const MAX_SHOWN: usize = 30;
    let mut seen = std::collections::HashSet::new();
    let mut shown = 0usize;
    for diagnostic in diagnostics {
        let location = describe_span(world, diagnostic);
        let key = format!("{}|{}", diagnostic.message, location);
        if !seen.insert(key) {
            continue;
        }
        if shown == MAX_SHOWN {
            logger.info(format!(
                "... {} more distinct diagnostic(s) not shown",
                diagnostics.len() - shown
            ));
            break;
        }
        shown += 1;
        let severity = match diagnostic.severity {
            Severity::Error => "error",
            Severity::Warning => "warning",
        };
        logger.info(format!(
            "typst {severity}: {}{}",
            diagnostic.message,
            if location.is_empty() {
                String::new()
            } else {
                format!(" [{location}]")
            }
        ));
        for hint in &diagnostic.hints {
            logger.verbose(format!("  hint: {}", hint.v));
        }
    }
}

fn describe_span(world: &NelsonWorld, diagnostic: &SourceDiagnostic) -> String {
    let Some(id) = diagnostic.span.id() else {
        return String::new();
    };
    let path = id.vpath().get_without_slash().to_string();
    match (world.source(id), world.range(diagnostic.span)) {
        (Ok(source), Some(range)) => {
            let line = source
                .lines()
                .byte_to_line(range.start)
                .map(|l| l + 1)
                .unwrap_or(0);
            format!("{path}:{line}")
        }
        _ => path,
    }
}

/// `typst/<lang>/main.typ` under `root`, if Nelson generated it.
pub fn language_main(root: &Path, language: &str) -> Option<PathBuf> {
    let path = root.join("typst").join(language).join("main.typ");
    path.is_file().then_some(path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn compiles_a_small_document_with_links_and_images() -> Result<()> {
        let dir = tempdir()?;
        fs::write(
            dir.path().join("page.typ"),
            "= Page <mod:page>\nSee #link(<mod:page>)[self] and #image(\"a.svg\").\n",
        )?;
        fs::write(
            dir.path().join("a.svg"),
            r#"<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10"><rect width="10" height="10" fill="red"/></svg>"#,
        )?;
        fs::write(
            dir.path().join("main.typ"),
            "#set page(numbering: \"1\")\n#outline()\n#pagebreak()\n#include \"page.typ\"\n",
        )?;
        let out = dir.path().join("out.pdf");

        let stats = compile_pdf(&dir.path().join("main.typ"), &out, Logger::new(false))?;

        assert_eq!(stats.pages, 2);
        let pdf = fs::read(&out)?;
        assert!(pdf.len() > 1000);
        let text = String::from_utf8_lossy(&pdf);
        assert!(text.contains("/CreationDate"), "creation date missing");
        assert!(text.contains("nelson-pdf-builder"), "creator missing");
        Ok(())
    }

    #[test]
    fn loader_downscales_wide_png_files() -> Result<()> {
        let dir = tempdir()?;
        fs::write(dir.path().join("main.typ"), "#image(\"wide.png\")\n")?;
        let mut png = Cursor::new(Vec::new());
        image::DynamicImage::new_rgb8(1600, 400).write_to(&mut png, image::ImageFormat::Png)?;
        fs::write(dir.path().join("wide.png"), png.into_inner())?;
        let world = NelsonWorld::new(&dir.path().join("main.typ"), Logger::new(false))?;

        let id = RootedPath::new(VirtualRoot::Project, VirtualPath::new("wide.png").unwrap())
            .intern();
        let bytes = world.file(id).unwrap();

        let loaded = image::load_from_memory(bytes.as_slice())?;
        assert_eq!((loaded.width(), loaded.height()), (800, 200));
        assert_eq!(
            world.files.loader().png_downscaled.load(Ordering::Relaxed),
            1
        );
        Ok(())
    }

    #[test]
    fn today_returns_a_date() {
        let dir = tempdir().unwrap();
        fs::write(dir.path().join("main.typ"), "").unwrap();
        let world = NelsonWorld::new(&dir.path().join("main.typ"), Logger::new(false)).unwrap();
        assert!(world.today(None).is_some());
        assert!(world.today(Some(Duration::from(time::Duration::hours(2)))).is_some());
    }

    #[test]
    fn reports_compile_errors() -> Result<()> {
        let dir = tempdir()?;
        fs::write(dir.path().join("main.typ"), "#include \"missing.typ\"\n")?;
        let err = compile_pdf(
            &dir.path().join("main.typ"),
            &dir.path().join("out.pdf"),
            Logger::new(false),
        )
        .unwrap_err();
        assert!(err.to_string().contains("compilation failed"), "{err}");
        Ok(())
    }

    #[test]
    fn downscales_embedded_png_bitmaps_only_when_too_wide() {
        use base64::Engine as _;
        let mut big = Cursor::new(Vec::new());
        image::DynamicImage::new_rgba8(1600, 400)
            .write_to(&mut big, image::ImageFormat::Png)
            .unwrap();
        let mut small = Cursor::new(Vec::new());
        image::DynamicImage::new_rgba8(200, 100)
            .write_to(&mut small, image::ImageFormat::Png)
            .unwrap();
        let b64 = base64::engine::general_purpose::STANDARD;
        let svg = format!(
            r#"<svg xmlns="http://www.w3.org/2000/svg"><image href="data:image/png;base64,{}"/><image href="data:image/png;base64,{}"/></svg>"#,
            b64.encode(big.into_inner()),
            b64.encode(small.into_inner())
        );

        let out = downscale_svg_bitmaps(&svg, 800).expect("big bitmap must be downscaled");
        assert!(out.len() < svg.len());
        let payloads: Vec<_> = out
            .split("data:image/png;base64,")
            .skip(1)
            .map(|p| p.split('"').next().unwrap())
            .collect();
        let first = image::load_from_memory(&b64.decode(payloads[0]).unwrap()).unwrap();
        assert_eq!((first.width(), first.height()), (800, 200));
        let second = image::load_from_memory(&b64.decode(payloads[1]).unwrap()).unwrap();
        assert_eq!((second.width(), second.height()), (200, 100));

        assert!(downscale_svg_bitmaps("<svg/>", 800).is_none());
    }

    #[test]
    fn language_main_requires_the_generated_file() -> Result<()> {
        let dir = tempdir()?;
        assert!(language_main(dir.path(), "en").is_none());
        fs::create_dir_all(dir.path().join("typst").join("en"))?;
        fs::write(dir.path().join("typst").join("en").join("main.typ"), "")?;
        assert!(language_main(dir.path(), "en").is_some());
        Ok(())
    }
}
