#import "nelson_help.typ": *

= jlrun <julia_engine:jlrun>

Run Julia statements from Nelson.

== Syntax

- #raw("jlrun(code)");
- #raw("outvars = jlrun(code, outputs)");
- #raw("outvars = jlrun(code, outputs, jlName, jlValue)");

== Input argument

/ code: a string scalar, string array, character vector, character array.
/ jlName, jlValue: Input arguments name and value
/ outputs: string array: Julia variable names.

== Output argument

/ outvars: One or more Nelson workspace variable names returned as valid Julia types.

== Description

#strong[jlrun(code)]; function executes Julia statements present in the code string within the Julia interpreter.

 Variables generated by the #strong[jlrun]; function remain persistent, allowing their usage in subsequent#strong[jlrun]; calls.

 #strong[outvars \= jlrun(code, outputs)]; Julia variables specified in outputs are returned to Nelson.

 The values of these variables are captured in#strong[outvars];.

 #strong[outvars \= jlrun(code, outputs, jlName, jlValue)];, the #strong[code]; is executed with assigned input and output variable names using Nelson data passed through one or more name-value arguments.


== Examples

``````matlab
jlrun('a = b * c', 'b', 5, 'c', 10)
r = jlrun('d = a + c', 'd')
``````

``````matlab
jlrun(["a = 3","print(a)"])
``````

``````matlab
[R1, R2] = jlrun("a=b*c",["a","b"], 'b', 5, 'c', 10)
``````


== See also

#nlink(<julia_engine:jlrunfile>)[jlrunfile];, #nlink(<julia_engine:jlenv>)[jlenv];, #nlink(<julia_engine:julia_types>)[Julia types supported];.

== History

#table(
  columns: 2,
  table.header([Version], [Description]),
  [1.12.0], [initial version],
)

// Author: Allan CORNET
